import {
  toProblemId,
  toSkillId,
  type CurriculumManifest,
  type Difficulty,
  type NonEmptyReadonlyArray,
  type ProblemSummary,
  type RealmId,
  type SkillSpec,
  type TrackId,
  type TrackSpec,
} from '../../../types/curriculum'
import {
  CURRICULUM_SOURCES,
  CURRICULUM_SOURCE_IDS,
  NEETCODE_REFERENCE_URL,
} from './sources'

export const NEETCODE_150_CONTENT_VERSION = 'v1.0.0' as const

const SKILL_DEFINITIONS = [
  { id: 'array-scan', label: 'Linear array scan', prerequisites: [] },
  {
    id: 'hash-membership',
    label: 'Hash membership lookup',
    prerequisites: ['array-scan'],
  },
  {
    id: 'frequency-map',
    label: 'Frequency map',
    prerequisites: ['hash-membership'],
  },
  {
    id: 'bucket-ranking',
    label: 'Frequency bucket ranking',
    prerequisites: ['frequency-map'],
  },
  {
    id: 'prefix-suffix',
    label: 'Prefix and suffix accumulation',
    prerequisites: ['array-scan'],
  },
  {
    id: 'length-prefix-codec',
    label: 'Length-prefix encoding',
    prerequisites: ['array-scan'],
  },
  {
    id: 'grid-constraint-sets',
    label: 'Grid constraint sets',
    prerequisites: ['hash-membership'],
  },
  {
    id: 'sequence-boundary-set',
    label: 'Sequence boundary expansion',
    prerequisites: ['hash-membership'],
  },
  {
    id: 'inward-two-pointers',
    label: 'Inward two-pointer scan',
    prerequisites: ['array-scan'],
  },
  {
    id: 'sorted-two-pointers',
    label: 'Sorted two-pointer search',
    prerequisites: ['inward-two-pointers'],
  },
  {
    id: 'three-sum-dedup',
    label: 'Sorted three-sum deduplication',
    prerequisites: ['sorted-two-pointers'],
  },
  {
    id: 'greedy-boundaries',
    label: 'Greedy boundary pairing',
    prerequisites: ['inward-two-pointers'],
  },
  {
    id: 'two-sided-water',
    label: 'Two-sided water bounds',
    prerequisites: ['greedy-boundaries'],
  },
  {
    id: 'variable-window',
    label: 'Variable sliding window',
    prerequisites: ['inward-two-pointers'],
  },
  {
    id: 'window-frequency',
    label: 'Window frequency accounting',
    prerequisites: ['frequency-map', 'variable-window'],
  },
  {
    id: 'monotonic-window',
    label: 'Monotonic window deque',
    prerequisites: ['variable-window'],
  },
  {
    id: 'stack-matching',
    label: 'Stack-based matching',
    prerequisites: ['array-scan'],
  },
  {
    id: 'augmented-stack',
    label: 'Augmented stack state',
    prerequisites: ['stack-matching'],
  },
  {
    id: 'postfix-stack',
    label: 'Postfix stack evaluation',
    prerequisites: ['stack-matching'],
  },
  {
    id: 'state-generation',
    label: 'Constrained state generation',
    prerequisites: ['stack-matching'],
  },
  {
    id: 'monotonic-stack',
    label: 'Monotonic stack',
    prerequisites: ['stack-matching'],
  },
  {
    id: 'histogram-boundaries',
    label: 'Histogram boundary expansion',
    prerequisites: ['monotonic-stack'],
  },
  {
    id: 'binary-search',
    label: 'Binary search invariant',
    prerequisites: ['array-scan'],
  },
  {
    id: 'matrix-search',
    label: 'Flattened matrix search',
    prerequisites: ['binary-search'],
  },
  {
    id: 'answer-search',
    label: 'Binary search on the answer',
    prerequisites: ['binary-search'],
  },
  {
    id: 'rotated-search',
    label: 'Rotated-array partition search',
    prerequisites: ['binary-search'],
  },
  {
    id: 'time-index-search',
    label: 'Time-indexed lookup',
    prerequisites: ['binary-search'],
  },
  {
    id: 'partition-search',
    label: 'Binary partition balancing',
    prerequisites: ['binary-search'],
  },
  { id: 'pointer-reversal', label: 'Pointer reversal', prerequisites: [] },
  {
    id: 'sorted-list-merge',
    label: 'Sorted list merge',
    prerequisites: ['pointer-reversal'],
  },
  {
    id: 'fast-slow-pointer',
    label: 'Fast and slow pointers',
    prerequisites: ['pointer-reversal'],
  },
  {
    id: 'list-splicing',
    label: 'Linked-list splicing',
    prerequisites: ['pointer-reversal'],
  },
  {
    id: 'node-map-copy',
    label: 'Node identity mapping',
    prerequisites: ['frequency-map'],
  },
  {
    id: 'linked-arithmetic',
    label: 'Linked digit arithmetic',
    prerequisites: ['list-splicing'],
  },
  {
    id: 'lru-design',
    label: 'Hash-linked cache design',
    prerequisites: ['list-splicing', 'node-map-copy'],
  },
  {
    id: 'divide-conquer-list-merge',
    label: 'Divide-and-conquer list merge',
    prerequisites: ['sorted-list-merge'],
  },
  {
    id: 'recursive-tree-dfs',
    label: 'Recursive tree depth-first search',
    prerequisites: ['state-generation'],
  },
  {
    id: 'tree-comparison',
    label: 'Paired tree comparison',
    prerequisites: ['recursive-tree-dfs'],
  },
  {
    id: 'level-order-bfs',
    label: 'Level-order breadth-first search',
    prerequisites: ['recursive-tree-dfs'],
  },
  {
    id: 'bst-invariant',
    label: 'BST range invariant',
    prerequisites: ['recursive-tree-dfs'],
  },
  {
    id: 'tree-reconstruction',
    label: 'Tree reconstruction by partitions',
    prerequisites: ['recursive-tree-dfs', 'hash-membership'],
  },
  {
    id: 'tree-rank',
    label: 'BST rank selection',
    prerequisites: ['bst-invariant'],
  },
  {
    id: 'path-aggregation',
    label: 'Tree path aggregation',
    prerequisites: ['recursive-tree-dfs'],
  },
  {
    id: 'tree-codec',
    label: 'Tree traversal codec',
    prerequisites: ['tree-reconstruction'],
  },
  {
    id: 'trie-operations',
    label: 'Trie prefix operations',
    prerequisites: ['frequency-map'],
  },
  {
    id: 'wildcard-trie',
    label: 'Wildcard trie search',
    prerequisites: ['trie-operations'],
  },
  {
    id: 'trie-grid-search',
    label: 'Trie-pruned grid search',
    prerequisites: ['trie-operations', 'state-generation'],
  },
  {
    id: 'heap-selection',
    label: 'Heap-based selection',
    prerequisites: ['array-scan'],
  },
  {
    id: 'streaming-heap',
    label: 'Streaming heap maintenance',
    prerequisites: ['heap-selection'],
  },
  {
    id: 'heap-scheduling',
    label: 'Heap scheduling',
    prerequisites: ['heap-selection', 'frequency-map'],
  },
  {
    id: 'multi-source-heap',
    label: 'Multi-source heap merge',
    prerequisites: ['heap-selection'],
  },
  {
    id: 'dual-heap',
    label: 'Dual-heap balancing',
    prerequisites: ['streaming-heap'],
  },
  {
    id: 'feed-merge',
    label: 'Ranked feed merge',
    prerequisites: ['multi-source-heap'],
  },
  {
    id: 'subset-backtracking',
    label: 'Subset decision backtracking',
    prerequisites: ['state-generation'],
  },
  {
    id: 'combination-backtracking',
    label: 'Combination backtracking',
    prerequisites: ['subset-backtracking'],
  },
  {
    id: 'permutation-backtracking',
    label: 'Permutation backtracking',
    prerequisites: ['subset-backtracking'],
  },
  {
    id: 'grid-backtracking',
    label: 'Grid path backtracking',
    prerequisites: ['state-generation'],
  },
  {
    id: 'palindrome-backtracking',
    label: 'Palindrome partition backtracking',
    prerequisites: ['state-generation'],
  },
  {
    id: 'constraint-backtracking',
    label: 'Constraint-driven backtracking',
    prerequisites: ['subset-backtracking'],
  },
  {
    id: 'grid-flood-fill',
    label: 'Grid flood fill',
    prerequisites: ['recursive-tree-dfs'],
  },
  {
    id: 'graph-dfs',
    label: 'Graph depth-first search',
    prerequisites: ['recursive-tree-dfs'],
  },
  {
    id: 'graph-bfs',
    label: 'Graph breadth-first search',
    prerequisites: ['level-order-bfs'],
  },
  {
    id: 'graph-cloning',
    label: 'Graph cloning with identity map',
    prerequisites: ['graph-dfs', 'node-map-copy'],
  },
  {
    id: 'topological-sort',
    label: 'Topological dependency ordering',
    prerequisites: ['graph-dfs'],
  },
  {
    id: 'union-find',
    label: 'Disjoint-set union',
    prerequisites: ['graph-dfs'],
  },
  {
    id: 'eulerian-path',
    label: 'Eulerian path reconstruction',
    prerequisites: ['graph-dfs'],
  },
  {
    id: 'minimum-spanning-tree',
    label: 'Minimum spanning tree',
    prerequisites: ['union-find', 'heap-selection'],
  },
  {
    id: 'dijkstra',
    label: 'Heap-based shortest path',
    prerequisites: ['graph-bfs', 'heap-selection'],
  },
  {
    id: 'minimax-path',
    label: 'Minimax shortest path',
    prerequisites: ['dijkstra'],
  },
  {
    id: 'topological-lexicon',
    label: 'Lexical topological ordering',
    prerequisites: ['topological-sort'],
  },
  {
    id: 'constrained-shortest-path',
    label: 'State-constrained shortest path',
    prerequisites: ['dijkstra'],
  },
  {
    id: 'linear-dp',
    label: 'Linear dynamic programming',
    prerequisites: ['array-scan'],
  },
  {
    id: 'take-skip-dp',
    label: 'Take-or-skip recurrence',
    prerequisites: ['linear-dp'],
  },
  {
    id: 'palindrome-dp',
    label: 'Palindrome expansion state',
    prerequisites: ['linear-dp'],
  },
  {
    id: 'coin-change-dp',
    label: 'Coin-change recurrence',
    prerequisites: ['linear-dp'],
  },
  {
    id: 'sequence-dp',
    label: 'Sequence dynamic programming',
    prerequisites: ['linear-dp'],
  },
  {
    id: 'word-segmentation-dp',
    label: 'Word segmentation recurrence',
    prerequisites: ['sequence-dp'],
  },
  {
    id: 'knapsack-dp',
    label: 'Subset-sum knapsack',
    prerequisites: ['coin-change-dp', 'sequence-dp'],
  },
  {
    id: 'grid-dp',
    label: 'Grid dynamic programming',
    prerequisites: ['linear-dp'],
  },
  {
    id: 'two-sequence-dp',
    label: 'Two-sequence dynamic programming',
    prerequisites: ['sequence-dp'],
  },
  {
    id: 'state-machine-dp',
    label: 'State-machine dynamic programming',
    prerequisites: ['linear-dp'],
  },
  {
    id: 'count-combination-dp',
    label: 'Combination-count dynamic programming',
    prerequisites: ['coin-change-dp'],
  },
  {
    id: 'string-interleaving-dp',
    label: 'Interleaving-string state',
    prerequisites: ['two-sequence-dp'],
  },
  {
    id: 'matrix-path-dp',
    label: 'Memoized matrix path',
    prerequisites: ['grid-dp', 'recursive-tree-dfs'],
  },
  {
    id: 'subsequence-count-dp',
    label: 'Subsequence counting state',
    prerequisites: ['two-sequence-dp'],
  },
  {
    id: 'edit-distance-dp',
    label: 'Edit-distance grid',
    prerequisites: ['two-sequence-dp'],
  },
  {
    id: 'interval-dp',
    label: 'Interval dynamic programming',
    prerequisites: ['sequence-dp'],
  },
  {
    id: 'regex-dp',
    label: 'Pattern-matching dynamic programming',
    prerequisites: ['two-sequence-dp'],
  },
  {
    id: 'kadane-scan',
    label: 'Kadane running optimum',
    prerequisites: ['linear-dp'],
  },
  {
    id: 'reachability-greedy',
    label: 'Greedy reachability frontier',
    prerequisites: ['array-scan'],
  },
  {
    id: 'jump-layer-greedy',
    label: 'Greedy jump layers',
    prerequisites: ['reachability-greedy'],
  },
  {
    id: 'circular-greedy',
    label: 'Circular greedy reset',
    prerequisites: ['reachability-greedy'],
  },
  {
    id: 'sorted-group-greedy',
    label: 'Sorted group consumption',
    prerequisites: ['sorted-two-pointers'],
  },
  {
    id: 'target-triplet-greedy',
    label: 'Target-bounded triplet merge',
    prerequisites: ['array-scan'],
  },
  {
    id: 'partition-greedy',
    label: 'Last-occurrence partitioning',
    prerequisites: ['frequency-map'],
  },
  {
    id: 'wildcard-bounds',
    label: 'Wildcard balance bounds',
    prerequisites: ['reachability-greedy'],
  },
  {
    id: 'interval-insertion',
    label: 'Ordered interval insertion',
    prerequisites: ['sorted-two-pointers'],
  },
  {
    id: 'interval-merge',
    label: 'Overlapping interval merge',
    prerequisites: ['interval-insertion'],
  },
  {
    id: 'interval-scheduling',
    label: 'Greedy interval scheduling',
    prerequisites: ['interval-merge'],
  },
  {
    id: 'meeting-sweep',
    label: 'Meeting-time sweep',
    prerequisites: ['interval-scheduling'],
  },
  {
    id: 'interval-heap',
    label: 'Active interval heap',
    prerequisites: ['meeting-sweep', 'heap-selection'],
  },
  {
    id: 'query-sweep',
    label: 'Offline interval query sweep',
    prerequisites: ['interval-heap'],
  },
  {
    id: 'matrix-rotation',
    label: 'Layered matrix rotation',
    prerequisites: ['grid-constraint-sets'],
  },
  {
    id: 'matrix-walk',
    label: 'Boundary-driven matrix walk',
    prerequisites: ['grid-constraint-sets'],
  },
  {
    id: 'matrix-marking',
    label: 'In-place matrix marking',
    prerequisites: ['grid-constraint-sets'],
  },
  {
    id: 'cycle-detection',
    label: 'State cycle detection',
    prerequisites: ['fast-slow-pointer'],
  },
  {
    id: 'carry-arithmetic',
    label: 'Carry-based arithmetic',
    prerequisites: ['array-scan'],
  },
  {
    id: 'fast-power',
    label: 'Exponentiation by squaring',
    prerequisites: ['binary-search'],
  },
  {
    id: 'digit-multiplication',
    label: 'Digit-array multiplication',
    prerequisites: ['carry-arithmetic'],
  },
  {
    id: 'coordinate-frequency',
    label: 'Coordinate frequency counting',
    prerequisites: ['frequency-map'],
  },
  {
    id: 'bitwise-operations',
    label: 'Bitwise operations',
    prerequisites: ['array-scan'],
  },
  {
    id: 'xor-cancellation',
    label: 'XOR cancellation',
    prerequisites: ['bitwise-operations'],
  },
  {
    id: 'bit-count',
    label: 'Set-bit counting',
    prerequisites: ['bitwise-operations'],
  },
  {
    id: 'bit-dp',
    label: 'Bit-count dynamic programming',
    prerequisites: ['bit-count', 'linear-dp'],
  },
  {
    id: 'bit-reversal',
    label: 'Fixed-width bit reversal',
    prerequisites: ['bitwise-operations'],
  },
  {
    id: 'xor-indexing',
    label: 'XOR index recovery',
    prerequisites: ['xor-cancellation'],
  },
  {
    id: 'bitwise-addition',
    label: 'Bitwise carry addition',
    prerequisites: ['bitwise-operations'],
  },
  {
    id: 'overflow-safe-arithmetic',
    label: 'Overflow-safe arithmetic',
    prerequisites: ['carry-arithmetic'],
  },
] as const

type SkillKey = (typeof SKILL_DEFINITIONS)[number]['id']

export const NEETCODE_150_SKILLS: readonly SkillSpec[] =
  SKILL_DEFINITIONS.map(({ id, label, prerequisites }) => ({
    id: toSkillId(id),
    patternLabel: label,
    prerequisiteSkillIds: prerequisites.map(toSkillId),
  }))

type ProblemSeed = {
  title: string
  slug: string
  difficulty: Difficulty
  skillKeys: NonEmptyReadonlyArray<SkillKey>
  prerequisiteSlugs: readonly string[]
}

const problem = (
  title: string,
  slug: string,
  difficulty: Difficulty,
  skillKeys: NonEmptyReadonlyArray<SkillKey>,
  prerequisiteSlugs: readonly string[] = [],
): ProblemSeed => ({
  title,
  slug,
  difficulty,
  skillKeys,
  prerequisiteSlugs,
})

type TrackSeed = {
  id: TrackId
  realmId: RealmId
  title: string
  realmOrder: 1 | 2 | 3
  globalStart: number
  problems: readonly ProblemSeed[]
}

const TRACK_SEEDS = [
  {
    id: 'arrays-hashing',
    realmId: 'realm1',
    title: 'Arrays & Hashing',
    realmOrder: 1,
    globalStart: 1,
    problems: [
      problem('Contains Duplicate', 'contains-duplicate', 'Easy', [
        'hash-membership',
      ]),
      problem(
        'Valid Anagram',
        'valid-anagram',
        'Easy',
        ['frequency-map'],
        ['contains-duplicate'],
      ),
      problem(
        'Two Sum',
        'two-sum',
        'Easy',
        ['frequency-map'],
        ['contains-duplicate'],
      ),
      problem(
        'Group Anagrams',
        'group-anagrams',
        'Medium',
        ['frequency-map'],
        ['valid-anagram'],
      ),
      problem(
        'Top K Frequent Elements',
        'top-k-frequent-elements',
        'Medium',
        ['frequency-map', 'bucket-ranking'],
        ['group-anagrams'],
      ),
      problem('Encode and Decode Strings', 'encode-and-decode-strings', 'Medium', [
        'length-prefix-codec',
      ]),
      problem(
        'Product of Array Except Self',
        'product-of-array-except-self',
        'Medium',
        ['prefix-suffix'],
      ),
      problem(
        'Valid Sudoku',
        'valid-sudoku',
        'Medium',
        ['grid-constraint-sets'],
        ['contains-duplicate'],
      ),
      problem(
        'Longest Consecutive Sequence',
        'longest-consecutive-sequence',
        'Medium',
        ['sequence-boundary-set'],
        ['contains-duplicate'],
      ),
    ],
  },
  {
    id: 'two-pointers',
    realmId: 'realm1',
    title: 'Two Pointers',
    realmOrder: 2,
    globalStart: 10,
    problems: [
      problem('Valid Palindrome', 'valid-palindrome', 'Easy', [
        'inward-two-pointers',
      ]),
      problem(
        'Two Sum II - Input Array Is Sorted',
        'two-sum-ii-input-array-is-sorted',
        'Medium',
        ['sorted-two-pointers'],
        ['two-sum'],
      ),
      problem(
        '3Sum',
        '3sum',
        'Medium',
        ['three-sum-dedup'],
        ['two-sum-ii-input-array-is-sorted'],
      ),
      problem(
        'Container With Most Water',
        'container-with-most-water',
        'Medium',
        ['greedy-boundaries'],
        ['valid-palindrome'],
      ),
      problem(
        'Trapping Rain Water',
        'trapping-rain-water',
        'Hard',
        ['two-sided-water'],
        ['container-with-most-water'],
      ),
    ],
  },
  {
    id: 'sliding-window',
    realmId: 'realm1',
    title: 'Sliding Window',
    realmOrder: 3,
    globalStart: 15,
    problems: [
      problem(
        'Best Time to Buy and Sell Stock',
        'best-time-to-buy-and-sell-stock',
        'Easy',
        ['variable-window'],
      ),
      problem(
        'Longest Substring Without Repeating Characters',
        'longest-substring-without-repeating-characters',
        'Medium',
        ['variable-window', 'hash-membership'],
        ['contains-duplicate'],
      ),
      problem(
        'Longest Repeating Character Replacement',
        'longest-repeating-character-replacement',
        'Medium',
        ['window-frequency'],
        ['longest-substring-without-repeating-characters'],
      ),
      problem(
        'Permutation in String',
        'permutation-in-string',
        'Medium',
        ['window-frequency'],
        ['valid-anagram', 'longest-substring-without-repeating-characters'],
      ),
      problem(
        'Minimum Window Substring',
        'minimum-window-substring',
        'Hard',
        ['window-frequency'],
        ['permutation-in-string'],
      ),
      problem(
        'Sliding Window Maximum',
        'sliding-window-maximum',
        'Hard',
        ['monotonic-window'],
        ['longest-repeating-character-replacement'],
      ),
    ],
  },
  {
    id: 'stack',
    realmId: 'realm2',
    title: 'Stack',
    realmOrder: 1,
    globalStart: 21,
    problems: [
      problem('Valid Parentheses', 'valid-parentheses', 'Easy', [
        'stack-matching',
      ]),
      problem(
        'Min Stack',
        'min-stack',
        'Medium',
        ['augmented-stack'],
        ['valid-parentheses'],
      ),
      problem(
        'Evaluate Reverse Polish Notation',
        'evaluate-reverse-polish-notation',
        'Medium',
        ['postfix-stack'],
        ['valid-parentheses'],
      ),
      problem(
        'Generate Parentheses',
        'generate-parentheses',
        'Medium',
        ['state-generation'],
        ['valid-parentheses'],
      ),
      problem(
        'Daily Temperatures',
        'daily-temperatures',
        'Medium',
        ['monotonic-stack'],
        ['min-stack'],
      ),
      problem(
        'Car Fleet',
        'car-fleet',
        'Medium',
        ['monotonic-stack'],
        ['daily-temperatures'],
      ),
      problem(
        'Largest Rectangle in Histogram',
        'largest-rectangle-in-histogram',
        'Hard',
        ['histogram-boundaries'],
        ['daily-temperatures'],
      ),
    ],
  },
  {
    id: 'binary-search',
    realmId: 'realm2',
    title: 'Binary Search',
    realmOrder: 2,
    globalStart: 28,
    problems: [
      problem('Binary Search', 'binary-search', 'Easy', ['binary-search']),
      problem(
        'Search a 2D Matrix',
        'search-a-2d-matrix',
        'Medium',
        ['matrix-search'],
        ['binary-search'],
      ),
      problem(
        'Koko Eating Bananas',
        'koko-eating-bananas',
        'Medium',
        ['answer-search'],
        ['binary-search'],
      ),
      problem(
        'Find Minimum in Rotated Sorted Array',
        'find-minimum-in-rotated-sorted-array',
        'Medium',
        ['rotated-search'],
        ['binary-search'],
      ),
      problem(
        'Search in Rotated Sorted Array',
        'search-in-rotated-sorted-array',
        'Medium',
        ['rotated-search'],
        ['find-minimum-in-rotated-sorted-array'],
      ),
      problem(
        'Time Based Key-Value Store',
        'time-based-key-value-store',
        'Medium',
        ['time-index-search', 'frequency-map'],
        ['binary-search'],
      ),
      problem(
        'Median of Two Sorted Arrays',
        'median-of-two-sorted-arrays',
        'Hard',
        ['partition-search'],
        ['binary-search'],
      ),
    ],
  },
  {
    id: 'linked-list',
    realmId: 'realm2',
    title: 'Linked List',
    realmOrder: 3,
    globalStart: 35,
    problems: [
      problem('Reverse Linked List', 'reverse-linked-list', 'Easy', [
        'pointer-reversal',
      ]),
      problem(
        'Merge Two Sorted Lists',
        'merge-two-sorted-lists',
        'Easy',
        ['sorted-list-merge'],
        ['reverse-linked-list'],
      ),
      problem(
        'Reorder List',
        'reorder-list',
        'Medium',
        ['fast-slow-pointer', 'list-splicing', 'pointer-reversal'],
        ['reverse-linked-list'],
      ),
      problem(
        'Remove Nth Node From End of List',
        'remove-nth-node-from-end-of-list',
        'Medium',
        ['fast-slow-pointer', 'list-splicing'],
        ['reorder-list'],
      ),
      problem(
        'Copy List with Random Pointer',
        'copy-list-with-random-pointer',
        'Medium',
        ['node-map-copy', 'list-splicing'],
        ['contains-duplicate'],
      ),
      problem(
        'Add Two Numbers',
        'add-two-numbers',
        'Medium',
        ['linked-arithmetic'],
        ['merge-two-sorted-lists'],
      ),
      problem(
        'Linked List Cycle',
        'linked-list-cycle',
        'Easy',
        ['fast-slow-pointer'],
        ['reverse-linked-list'],
      ),
      problem(
        'Find the Duplicate Number',
        'find-the-duplicate-number',
        'Medium',
        ['fast-slow-pointer'],
        ['linked-list-cycle'],
      ),
      problem(
        'LRU Cache',
        'lru-cache',
        'Medium',
        ['lru-design'],
        ['reorder-list', 'copy-list-with-random-pointer'],
      ),
      problem(
        'Merge k Sorted Lists',
        'merge-k-sorted-lists',
        'Hard',
        ['divide-conquer-list-merge'],
        ['merge-two-sorted-lists'],
      ),
      problem(
        'Reverse Nodes in k-Group',
        'reverse-nodes-in-k-group',
        'Hard',
        ['list-splicing', 'pointer-reversal'],
        ['reverse-linked-list'],
      ),
    ],
  },
  {
    id: 'trees',
    realmId: 'realm3',
    title: 'Trees',
    realmOrder: 1,
    globalStart: 46,
    problems: [
      problem('Invert Binary Tree', 'invert-binary-tree', 'Easy', [
        'recursive-tree-dfs',
      ]),
      problem(
        'Maximum Depth of Binary Tree',
        'maximum-depth-of-binary-tree',
        'Easy',
        ['recursive-tree-dfs'],
        ['invert-binary-tree'],
      ),
      problem(
        'Diameter of Binary Tree',
        'diameter-of-binary-tree',
        'Easy',
        ['path-aggregation'],
        ['maximum-depth-of-binary-tree'],
      ),
      problem(
        'Balanced Binary Tree',
        'balanced-binary-tree',
        'Easy',
        ['path-aggregation'],
        ['maximum-depth-of-binary-tree'],
      ),
      problem(
        'Same Tree',
        'same-tree',
        'Easy',
        ['tree-comparison'],
        ['invert-binary-tree'],
      ),
      problem(
        'Subtree of Another Tree',
        'subtree-of-another-tree',
        'Easy',
        ['tree-comparison'],
        ['same-tree'],
      ),
      problem(
        'Lowest Common Ancestor of a Binary Search Tree',
        'lowest-common-ancestor-of-a-binary-search-tree',
        'Medium',
        ['bst-invariant'],
        ['maximum-depth-of-binary-tree'],
      ),
      problem(
        'Binary Tree Level Order Traversal',
        'binary-tree-level-order-traversal',
        'Medium',
        ['level-order-bfs'],
        ['maximum-depth-of-binary-tree'],
      ),
      problem(
        'Binary Tree Right Side View',
        'binary-tree-right-side-view',
        'Medium',
        ['level-order-bfs'],
        ['binary-tree-level-order-traversal'],
      ),
      problem(
        'Count Good Nodes in Binary Tree',
        'count-good-nodes-in-binary-tree',
        'Medium',
        ['path-aggregation'],
        ['maximum-depth-of-binary-tree'],
      ),
      problem(
        'Validate Binary Search Tree',
        'validate-binary-search-tree',
        'Medium',
        ['bst-invariant'],
        ['same-tree'],
      ),
      problem(
        'Kth Smallest Element in a BST',
        'kth-smallest-element-in-a-bst',
        'Medium',
        ['tree-rank', 'bst-invariant'],
        ['validate-binary-search-tree'],
      ),
      problem(
        'Construct Binary Tree from Preorder and Inorder Traversal',
        'construct-binary-tree-from-preorder-and-inorder-traversal',
        'Medium',
        ['tree-reconstruction'],
        ['binary-tree-level-order-traversal'],
      ),
      problem(
        'Binary Tree Maximum Path Sum',
        'binary-tree-maximum-path-sum',
        'Hard',
        ['path-aggregation'],
        ['diameter-of-binary-tree'],
      ),
      problem(
        'Serialize and Deserialize Binary Tree',
        'serialize-and-deserialize-binary-tree',
        'Hard',
        ['tree-codec'],
        ['construct-binary-tree-from-preorder-and-inorder-traversal'],
      ),
    ],
  },
  {
    id: 'tries',
    realmId: 'realm3',
    title: 'Tries',
    realmOrder: 2,
    globalStart: 61,
    problems: [
      problem(
        'Implement Trie (Prefix Tree)',
        'implement-trie-prefix-tree',
        'Medium',
        ['trie-operations'],
      ),
      problem(
        'Design Add and Search Words Data Structure',
        'design-add-and-search-words-data-structure',
        'Medium',
        ['wildcard-trie'],
        ['implement-trie-prefix-tree'],
      ),
      problem(
        'Word Search II',
        'word-search-ii',
        'Hard',
        ['trie-grid-search'],
        ['design-add-and-search-words-data-structure'],
      ),
    ],
  },
  {
    id: 'heap-priority-queue',
    realmId: 'realm3',
    title: 'Heap / Priority Queue',
    realmOrder: 3,
    globalStart: 64,
    problems: [
      problem(
        'Kth Largest Element in a Stream',
        'kth-largest-element-in-a-stream',
        'Easy',
        ['streaming-heap'],
      ),
      problem(
        'Last Stone Weight',
        'last-stone-weight',
        'Easy',
        ['heap-selection'],
        ['kth-largest-element-in-a-stream'],
      ),
      problem(
        'K Closest Points to Origin',
        'k-closest-points-to-origin',
        'Medium',
        ['heap-selection'],
        ['last-stone-weight'],
      ),
      problem(
        'Kth Largest Element in an Array',
        'kth-largest-element-in-an-array',
        'Medium',
        ['heap-selection'],
        ['kth-largest-element-in-a-stream'],
      ),
      problem(
        'Task Scheduler',
        'task-scheduler',
        'Medium',
        ['heap-scheduling'],
        ['top-k-frequent-elements'],
      ),
      problem(
        'Design Twitter',
        'design-twitter',
        'Medium',
        ['feed-merge', 'multi-source-heap'],
        ['kth-largest-element-in-an-array'],
      ),
      problem(
        'Find Median from Data Stream',
        'find-median-from-data-stream',
        'Hard',
        ['dual-heap'],
        ['kth-largest-element-in-a-stream'],
      ),
    ],
  },
  {
    id: 'backtracking',
    realmId: 'realm4',
    title: 'Backtracking',
    realmOrder: 1,
    globalStart: 71,
    problems: [
      problem(
        'Subsets',
        'subsets',
        'Medium',
        ['subset-backtracking'],
        ['generate-parentheses'],
      ),
      problem(
        'Combination Sum',
        'combination-sum',
        'Medium',
        ['combination-backtracking'],
        ['subsets'],
      ),
      problem(
        'Permutations',
        'permutations',
        'Medium',
        ['permutation-backtracking'],
        ['subsets'],
      ),
      problem(
        'Subsets II',
        'subsets-ii',
        'Medium',
        ['subset-backtracking'],
        ['subsets'],
      ),
      problem(
        'Combination Sum II',
        'combination-sum-ii',
        'Medium',
        ['combination-backtracking'],
        ['combination-sum', 'subsets-ii'],
      ),
      problem(
        'Word Search',
        'word-search',
        'Medium',
        ['grid-backtracking'],
        ['subsets'],
      ),
      problem(
        'Palindrome Partitioning',
        'palindrome-partitioning',
        'Medium',
        ['palindrome-backtracking'],
        ['valid-palindrome', 'subsets'],
      ),
      problem(
        'Letter Combinations of a Phone Number',
        'letter-combinations-of-a-phone-number',
        'Medium',
        ['combination-backtracking'],
        ['subsets'],
      ),
      problem(
        'N-Queens',
        'n-queens',
        'Hard',
        ['constraint-backtracking'],
        ['combination-sum', 'permutations'],
      ),
    ],
  },
  {
    id: 'graphs',
    realmId: 'realm4',
    title: 'Graphs',
    realmOrder: 2,
    globalStart: 80,
    problems: [
      problem(
        'Number of Islands',
        'number-of-islands',
        'Medium',
        ['grid-flood-fill'],
        ['word-search'],
      ),
      problem(
        'Max Area of Island',
        'max-area-of-island',
        'Medium',
        ['grid-flood-fill'],
        ['number-of-islands'],
      ),
      problem(
        'Clone Graph',
        'clone-graph',
        'Medium',
        ['graph-cloning'],
        ['number-of-islands'],
      ),
      problem(
        'Walls and Gates',
        'walls-and-gates',
        'Medium',
        ['graph-bfs', 'grid-flood-fill'],
        ['number-of-islands'],
      ),
      problem(
        'Rotting Oranges',
        'rotting-oranges',
        'Medium',
        ['graph-bfs'],
        ['walls-and-gates'],
      ),
      problem(
        'Pacific Atlantic Water Flow',
        'pacific-atlantic-water-flow',
        'Medium',
        ['grid-flood-fill'],
        ['number-of-islands'],
      ),
      problem(
        'Surrounded Regions',
        'surrounded-regions',
        'Medium',
        ['grid-flood-fill'],
        ['pacific-atlantic-water-flow'],
      ),
      problem(
        'Course Schedule',
        'course-schedule',
        'Medium',
        ['topological-sort'],
        ['clone-graph'],
      ),
      problem(
        'Course Schedule II',
        'course-schedule-ii',
        'Medium',
        ['topological-sort'],
        ['course-schedule'],
      ),
      problem(
        'Graph Valid Tree',
        'graph-valid-tree',
        'Medium',
        ['union-find', 'graph-dfs'],
        ['clone-graph'],
      ),
      problem(
        'Number of Connected Components in an Undirected Graph',
        'number-of-connected-components-in-an-undirected-graph',
        'Medium',
        ['union-find'],
        ['graph-valid-tree'],
      ),
      problem(
        'Redundant Connection',
        'redundant-connection',
        'Medium',
        ['union-find'],
        ['number-of-connected-components-in-an-undirected-graph'],
      ),
      problem(
        'Word Ladder',
        'word-ladder',
        'Hard',
        ['graph-bfs', 'frequency-map'],
        ['rotting-oranges', 'course-schedule'],
      ),
    ],
  },
  {
    id: 'advanced-graphs',
    realmId: 'realm4',
    title: 'Advanced Graphs',
    realmOrder: 3,
    globalStart: 93,
    problems: [
      problem(
        'Reconstruct Itinerary',
        'reconstruct-itinerary',
        'Hard',
        ['eulerian-path'],
        ['course-schedule-ii'],
      ),
      problem(
        'Min Cost to Connect All Points',
        'min-cost-to-connect-all-points',
        'Medium',
        ['minimum-spanning-tree'],
        ['redundant-connection'],
      ),
      problem(
        'Network Delay Time',
        'network-delay-time',
        'Medium',
        ['dijkstra'],
        ['course-schedule'],
      ),
      problem(
        'Swim in Rising Water',
        'swim-in-rising-water',
        'Hard',
        ['minimax-path'],
        ['network-delay-time'],
      ),
      problem(
        'Alien Dictionary',
        'alien-dictionary',
        'Hard',
        ['topological-lexicon'],
        ['course-schedule-ii'],
      ),
      problem(
        'Cheapest Flights Within K Stops',
        'cheapest-flights-within-k-stops',
        'Medium',
        ['constrained-shortest-path'],
        ['network-delay-time'],
      ),
    ],
  },
  {
    id: '1d-dp',
    realmId: 'realm5',
    title: '1-D Dynamic Programming',
    realmOrder: 1,
    globalStart: 99,
    problems: [
      problem('Climbing Stairs', 'climbing-stairs', 'Easy', ['linear-dp']),
      problem(
        'Min Cost Climbing Stairs',
        'min-cost-climbing-stairs',
        'Easy',
        ['linear-dp'],
        ['climbing-stairs'],
      ),
      problem(
        'House Robber',
        'house-robber',
        'Medium',
        ['take-skip-dp'],
        ['climbing-stairs'],
      ),
      problem(
        'House Robber II',
        'house-robber-ii',
        'Medium',
        ['take-skip-dp'],
        ['house-robber'],
      ),
      problem(
        'Longest Palindromic Substring',
        'longest-palindromic-substring',
        'Medium',
        ['palindrome-dp'],
        ['palindrome-partitioning'],
      ),
      problem(
        'Palindromic Substrings',
        'palindromic-substrings',
        'Medium',
        ['palindrome-dp'],
        ['longest-palindromic-substring'],
      ),
      problem(
        'Decode Ways',
        'decode-ways',
        'Medium',
        ['sequence-dp'],
        ['climbing-stairs'],
      ),
      problem(
        'Coin Change',
        'coin-change',
        'Medium',
        ['coin-change-dp'],
        ['min-cost-climbing-stairs'],
      ),
      problem(
        'Maximum Product Subarray',
        'maximum-product-subarray',
        'Medium',
        ['linear-dp'],
        ['product-of-array-except-self'],
      ),
      problem(
        'Word Break',
        'word-break',
        'Medium',
        ['word-segmentation-dp'],
        ['decode-ways'],
      ),
      problem(
        'Longest Increasing Subsequence',
        'longest-increasing-subsequence',
        'Medium',
        ['sequence-dp'],
        ['climbing-stairs'],
      ),
      problem(
        'Partition Equal Subset Sum',
        'partition-equal-subset-sum',
        'Medium',
        ['knapsack-dp'],
        ['coin-change', 'house-robber'],
      ),
    ],
  },
  {
    id: '2d-dp',
    realmId: 'realm5',
    title: '2-D Dynamic Programming',
    realmOrder: 2,
    globalStart: 111,
    problems: [
      problem(
        'Unique Paths',
        'unique-paths',
        'Medium',
        ['grid-dp'],
        ['climbing-stairs'],
      ),
      problem(
        'Longest Common Subsequence',
        'longest-common-subsequence',
        'Medium',
        ['two-sequence-dp'],
        ['longest-increasing-subsequence'],
      ),
      problem(
        'Best Time to Buy and Sell Stock with Cooldown',
        'best-time-to-buy-and-sell-stock-with-cooldown',
        'Medium',
        ['state-machine-dp'],
        ['best-time-to-buy-and-sell-stock', 'house-robber'],
      ),
      problem(
        'Coin Change II',
        'coin-change-ii',
        'Medium',
        ['count-combination-dp'],
        ['coin-change'],
      ),
      problem(
        'Target Sum',
        'target-sum',
        'Medium',
        ['knapsack-dp'],
        ['partition-equal-subset-sum'],
      ),
      problem(
        'Interleaving String',
        'interleaving-string',
        'Medium',
        ['string-interleaving-dp'],
        ['longest-common-subsequence'],
      ),
      problem(
        'Longest Increasing Path in a Matrix',
        'longest-increasing-path-in-a-matrix',
        'Hard',
        ['matrix-path-dp'],
        ['longest-increasing-subsequence', 'number-of-islands'],
      ),
      problem(
        'Distinct Subsequences',
        'distinct-subsequences',
        'Hard',
        ['subsequence-count-dp'],
        ['longest-common-subsequence'],
      ),
      problem(
        'Edit Distance',
        'edit-distance',
        'Medium',
        ['edit-distance-dp'],
        ['longest-common-subsequence'],
      ),
      problem(
        'Burst Balloons',
        'burst-balloons',
        'Hard',
        ['interval-dp'],
        ['maximum-product-subarray'],
      ),
      problem(
        'Regular Expression Matching',
        'regular-expression-matching',
        'Hard',
        ['regex-dp'],
        ['edit-distance'],
      ),
    ],
  },
  {
    id: 'greedy',
    realmId: 'realm5',
    title: 'Greedy',
    realmOrder: 3,
    globalStart: 122,
    problems: [
      problem(
        'Maximum Subarray',
        'maximum-subarray',
        'Medium',
        ['kadane-scan'],
        ['maximum-product-subarray'],
      ),
      problem(
        'Jump Game',
        'jump-game',
        'Medium',
        ['reachability-greedy'],
        ['climbing-stairs'],
      ),
      problem(
        'Jump Game II',
        'jump-game-ii',
        'Medium',
        ['jump-layer-greedy'],
        ['jump-game'],
      ),
      problem(
        'Gas Station',
        'gas-station',
        'Medium',
        ['circular-greedy'],
        ['jump-game'],
      ),
      problem(
        'Hand of Straights',
        'hand-of-straights',
        'Medium',
        ['sorted-group-greedy', 'frequency-map'],
        ['top-k-frequent-elements'],
      ),
      problem(
        'Merge Triplets to Form Target Triplet',
        'merge-triplets-to-form-target-triplet',
        'Medium',
        ['target-triplet-greedy'],
        ['product-of-array-except-self'],
      ),
      problem(
        'Partition Labels',
        'partition-labels',
        'Medium',
        ['partition-greedy'],
        ['valid-anagram'],
      ),
      problem(
        'Valid Parenthesis String',
        'valid-parenthesis-string',
        'Medium',
        ['wildcard-bounds'],
        ['generate-parentheses'],
      ),
    ],
  },
  {
    id: 'intervals',
    realmId: 'realm6',
    title: 'Intervals',
    realmOrder: 1,
    globalStart: 130,
    problems: [
      problem('Insert Interval', 'insert-interval', 'Medium', [
        'interval-insertion',
      ]),
      problem(
        'Merge Intervals',
        'merge-intervals',
        'Medium',
        ['interval-merge'],
        ['insert-interval'],
      ),
      problem(
        'Non-overlapping Intervals',
        'non-overlapping-intervals',
        'Medium',
        ['interval-scheduling'],
        ['merge-intervals'],
      ),
      problem(
        'Meeting Rooms',
        'meeting-rooms',
        'Easy',
        ['meeting-sweep'],
        ['non-overlapping-intervals'],
      ),
      problem(
        'Meeting Rooms II',
        'meeting-rooms-ii',
        'Medium',
        ['interval-heap', 'meeting-sweep'],
        ['meeting-rooms'],
      ),
      problem(
        'Minimum Interval to Include Each Query',
        'minimum-interval-to-include-each-query',
        'Hard',
        ['query-sweep'],
        ['meeting-rooms-ii', 'sliding-window-maximum'],
      ),
    ],
  },
  {
    id: 'math-geometry',
    realmId: 'realm6',
    title: 'Math & Geometry',
    realmOrder: 2,
    globalStart: 136,
    problems: [
      problem(
        'Rotate Image',
        'rotate-image',
        'Medium',
        ['matrix-rotation'],
        ['valid-sudoku'],
      ),
      problem(
        'Spiral Matrix',
        'spiral-matrix',
        'Medium',
        ['matrix-walk'],
        ['rotate-image'],
      ),
      problem(
        'Set Matrix Zeroes',
        'set-matrix-zeroes',
        'Medium',
        ['matrix-marking'],
        ['rotate-image'],
      ),
      problem(
        'Happy Number',
        'happy-number',
        'Easy',
        ['cycle-detection'],
        ['linked-list-cycle'],
      ),
      problem(
        'Plus One',
        'plus-one',
        'Easy',
        ['carry-arithmetic'],
        ['add-two-numbers'],
      ),
      problem(
        'Pow(x, n)',
        'powx-n',
        'Medium',
        ['fast-power'],
        ['binary-search'],
      ),
      problem(
        'Multiply Strings',
        'multiply-strings',
        'Medium',
        ['digit-multiplication'],
        ['plus-one'],
      ),
      problem(
        'Detect Squares',
        'detect-squares',
        'Medium',
        ['coordinate-frequency'],
        ['contains-duplicate'],
      ),
    ],
  },
  {
    id: 'bit-manipulation',
    realmId: 'realm6',
    title: 'Bit Manipulation',
    realmOrder: 3,
    globalStart: 144,
    problems: [
      problem('Single Number', 'single-number', 'Easy', ['xor-cancellation']),
      problem(
        'Number of 1 Bits',
        'number-of-1-bits',
        'Easy',
        ['bit-count'],
        ['single-number'],
      ),
      problem(
        'Counting Bits',
        'counting-bits',
        'Easy',
        ['bit-dp'],
        ['number-of-1-bits'],
      ),
      problem(
        'Reverse Bits',
        'reverse-bits',
        'Easy',
        ['bit-reversal'],
        ['number-of-1-bits'],
      ),
      problem(
        'Missing Number',
        'missing-number',
        'Easy',
        ['xor-indexing'],
        ['single-number'],
      ),
      problem(
        'Sum of Two Integers',
        'sum-of-two-integers',
        'Medium',
        ['bitwise-addition'],
        ['number-of-1-bits'],
      ),
      problem(
        'Reverse Integer',
        'reverse-integer',
        'Medium',
        ['overflow-safe-arithmetic'],
        ['sum-of-two-integers'],
      ),
    ],
  },
] as const satisfies readonly TrackSeed[]

export const NEETCODE_150_PROBLEMS: readonly ProblemSummary[] =
  TRACK_SEEDS.flatMap((track) =>
    track.problems.map((entry, index) => {
      const [firstSkill, ...remainingSkills] = entry.skillKeys

      return {
        id: toProblemId(entry.slug),
        title: entry.title,
        leetcodeSlug: entry.slug,
        difficulty: entry.difficulty,
        realmId: track.realmId,
        trackId: track.id,
        globalOrder: track.globalStart + index,
        trackOrder: index + 1,
        skillIds: [
          toSkillId(firstSkill),
          ...remainingSkills.map(toSkillId),
        ],
        prerequisiteProblemIds: entry.prerequisiteSlugs.map(toProblemId),
        referenceUrl: `https://leetcode.com/problems/${entry.slug}/`,
        contentVersion: NEETCODE_150_CONTENT_VERSION,
        provenance: {
          primaryReferenceSourceId: CURRICULUM_SOURCE_IDS.neetcodeReference,
          curriculumVerificationSourceId:
            CURRICULUM_SOURCE_IDS.curriculumVerification,
          pedagogySourceIds: [
            CURRICULUM_SOURCE_IDS.openDsa,
            CURRICULUM_SOURCE_IDS.openDataStructures,
          ],
          sourceReferenceUrl: NEETCODE_REFERENCE_URL,
          promptsAndStatements: 'original',
          copiedSourceMaterial: false,
        },
      }
    }),
  )

export const NEETCODE_150_TRACKS: readonly TrackSpec[] = TRACK_SEEDS.map(
  (track) => {
    const problemIds = track.problems.map((entry) => toProblemId(entry.slug))
    const skillIds = [
      ...new Set(
        track.problems.flatMap((entry) => entry.skillKeys.map(toSkillId)),
      ),
    ]

    return {
      id: track.id,
      realmId: track.realmId,
      title: track.title,
      realmOrder: track.realmOrder,
      problemCount: problemIds.length,
      problemIds,
      skillIds,
    }
  },
)

export const NEETCODE_150_REALMS = [
  {
    id: 'realm1',
    title: 'Foundations of Sequences',
    order: 1,
    trackIds: ['arrays-hashing', 'two-pointers', 'sliding-window'],
  },
  {
    id: 'realm2',
    title: 'Ordered Structures',
    order: 2,
    trackIds: ['stack', 'binary-search', 'linked-list'],
  },
  {
    id: 'realm3',
    title: 'Hierarchies and Priority',
    order: 3,
    trackIds: ['trees', 'tries', 'heap-priority-queue'],
  },
  {
    id: 'realm4',
    title: 'Search and Networks',
    order: 4,
    trackIds: ['backtracking', 'graphs', 'advanced-graphs'],
  },
  {
    id: 'realm5',
    title: 'Optimization',
    order: 5,
    trackIds: ['1d-dp', '2d-dp', 'greedy'],
  },
  {
    id: 'realm6',
    title: 'Ranges, Geometry, and Bits',
    order: 6,
    trackIds: ['intervals', 'math-geometry', 'bit-manipulation'],
  },
] as const satisfies CurriculumManifest['realms']

export const NEETCODE_150_MANIFEST = {
  id: 'curriculum:neetcode150',
  title: 'NeetCode 150 Mastery',
  version: {
    schema: 'v1.0.0',
    content: NEETCODE_150_CONTENT_VERSION,
    releasedAt: '2026-07-11',
  },
  masteryPolicy: {
    version: 'v1.0.0',
    requiredEvidence: [
      'acquisition',
      'independent-transfer',
      'delayed-retrieval',
      'code-tests',
    ],
    acquisitionMinimumScore: 0.8,
    transferMinimumScore: 0.8,
    delayedRetrievalMinimumScore: 0.8,
    delayedRetrievalMinimumHours: 24,
    requiredDelayedRetrievals: 1,
    bossMinimumScore: 0.8,
    requiresAllTrackCoverage: true,
    requiresPassingCodeTests: true,
  },
  contentPolicy: {
    promptAuthorship: 'original',
    copiedThirdPartyStatements: false,
    copiedThirdPartyEditorials: false,
    prohibitedContentSources: [
      'neetcode.io pages or APIs',
      'LeetCode problem statements and editorials',
      'NeetCode editorials and written explanations',
      'NeetCode or LeetCode video transcripts',
    ],
    metadataOnlyFields: [
      'title',
      'leetcodeSlug',
      'difficulty',
      'referenceUrl',
    ],
  },
  sources: CURRICULUM_SOURCES,
  skills: NEETCODE_150_SKILLS,
  realms: NEETCODE_150_REALMS,
  tracks: NEETCODE_150_TRACKS,
  problems: NEETCODE_150_PROBLEMS,
} as const satisfies CurriculumManifest
