/* eslint-disable */
// GENERATED FILE — written by `npm run meshy:optimize` (scripts/meshy-optimize.mjs).
// Do not edit by hand; re-run the optimizer after regenerating Meshy assets.
//
// Staging manifest for Meshy-AI-generated assets under public/assets/meshy/.
// Deliberately separate from assetManifest.ts (CC0 starter pipeline) — scene
// integration decides later which of these ship in district bundles.

/** Provenance/license block attached to every Meshy-generated asset. */
export interface MeshyAssetLicense {
  source: 'meshy-ai-generated'
  holder: string
  url: string
}

export type MeshyAssetCategory = "street" | "vehicle" | "nature" | "interact" | "landmark" | "dojo" | "arena" | "character" | "storefront" | "rooftop" | "structure"

export interface MeshyAssetEntry {
  /** Stable id — catalog id, with a clip suffix for character animations. */
  id: string
  /** Site-root-relative URL (prefix with import.meta.env.BASE_URL). */
  url: string
  category: MeshyAssetCategory
  /** Rendered triangles after optimization (approximate). */
  approxTriangles: number
  /** Exact size on disk of the shipped (optimized) file. */
  bytes: number
  license: MeshyAssetLicense
  /** Where scenes are expected to place this asset. */
  placementHint: string
}

export const MESHY_LICENSE: MeshyAssetLicense = {
  source: 'meshy-ai-generated',
  holder: 'project-owned (Meshy paid-plan generated asset)',
  url: 'https://www.meshy.ai',
}

export const MESHY_ASSETS: MeshyAssetEntry[] = [
  {
    id: "arena-alley-signstack",
    url: "assets/meshy/arena/arena-alley-signstack.glb",
    category: "arena",
    approxTriangles: 8485,
    bytes: 405536,
    license: MESHY_LICENSE,
    placementHint: "The Hider arena (variant 0) — shadow-alley signage anchors around the ring.",
  },
  {
    id: "arena-container-stack",
    url: "assets/meshy/arena/arena-container-stack.glb",
    category: "arena",
    approxTriangles: 7930,
    bytes: 359524,
    license: MESHY_LICENSE,
    placementHint: "Bracket Beast arena (variant 4) — collapsed industrial yard perimeter.",
  },
  {
    id: "arena-core-throne",
    url: "assets/meshy/arena/arena-core-throne.glb",
    category: "arena",
    approxTriangles: 19884,
    bytes: 565312,
    license: MESHY_LICENSE,
    placementHint: "Boss arena backdrop — Vex spawn point; faces the arena center.",
  },
  {
    id: "arena-corrupted-obelisk",
    url: "assets/meshy/arena/arena-corrupted-obelisk.glb",
    category: "arena",
    approxTriangles: 12078,
    bytes: 582720,
    license: MESHY_LICENSE,
    placementHint: "Boss arena perimeter markers and corruption zones.",
  },
  {
    id: "arena-debris-barricade",
    url: "assets/meshy/arena/arena-debris-barricade.glb",
    category: "arena",
    approxTriangles: 8205,
    bytes: 358180,
    license: MESHY_LICENSE,
    placementHint: "Arena cover objects; scatter 3-5 chunks between the pillars.",
  },
  {
    id: "arena-energy-pylon",
    url: "assets/meshy/arena/arena-energy-pylon.glb",
    category: "arena",
    approxTriangles: 10871,
    bytes: 712316,
    license: MESHY_LICENSE,
    placementHint: "Boss arena corners; combat objective / hazard anchor.",
  },
  {
    id: "arena-firewall-panel",
    url: "assets/meshy/arena/arena-firewall-panel.glb",
    category: "arena",
    approxTriangles: 2466,
    bytes: 662520,
    license: MESHY_LICENSE,
    placementHint: "Boss arena cover objects; breach storytelling.",
  },
  {
    id: "arena-floor-emblem",
    url: "assets/meshy/arena/arena-floor-emblem.glb",
    category: "arena",
    approxTriangles: 9936,
    bytes: 732836,
    license: MESHY_LICENSE,
    placementHint: "Boss arena center — the fight happens on top of it; flat disc, origin at bottom.",
  },
  {
    id: "arena-holo-ring",
    url: "assets/meshy/arena/arena-holo-ring.glb",
    category: "arena",
    approxTriangles: 8206,
    bytes: 744576,
    license: MESHY_LICENSE,
    placementHint: "Hangs over the arena center at a dramatic tilt; the \"sexy\" skyline of the fight.",
  },
  {
    id: "arena-holo-warning",
    url: "assets/meshy/arena/arena-holo-warning.glb",
    category: "arena",
    approxTriangles: 5628,
    bytes: 289812,
    license: MESHY_LICENSE,
    placementHint: "Arena entrance flank and breach walls; crimson glitch storytelling.",
  },
  {
    id: "arena-mirror-monolith",
    url: "assets/meshy/arena/arena-mirror-monolith.glb",
    category: "arena",
    approxTriangles: 7650,
    bytes: 206912,
    license: MESHY_LICENSE,
    placementHint: "Mirror Mimic arena (variant 1) — mirrored atrium monolith ring.",
  },
  {
    id: "arena-pillar-conduit",
    url: "assets/meshy/arena/arena-pillar-conduit.glb",
    category: "arena",
    approxTriangles: 6982,
    bytes: 282368,
    license: MESHY_LICENSE,
    placementHint: "Arena perimeter ring; tall crimson vertical, pairs with arena-energy-pylon (cyan).",
  },
  {
    id: "arena-pillar-holo",
    url: "assets/meshy/arena/arena-pillar-holo.glb",
    category: "arena",
    approxTriangles: 5215,
    bytes: 249076,
    license: MESHY_LICENSE,
    placementHint: "Arena mid-ring accents; cool cyan contrast between the crimson pillars.",
  },
  {
    id: "arena-pillar-shard",
    url: "assets/meshy/arena/arena-pillar-shard.glb",
    category: "arena",
    approxTriangles: 6991,
    bytes: 261864,
    license: MESHY_LICENSE,
    placementHint: "Arena corners; taller sibling of arena-corrupted-obelisk.",
  },
  {
    id: "arena-pillar-vent",
    url: "assets/meshy/arena/arena-pillar-vent.glb",
    category: "arena",
    approxTriangles: 6173,
    bytes: 242696,
    license: MESHY_LICENSE,
    placementHint: "Arena outer ring; amber hazard vertical, breaks up the crimson/cyan rhythm.",
  },
  {
    id: "arena-quarry-excavator",
    url: "assets/meshy/arena/arena-quarry-excavator.glb",
    category: "arena",
    approxTriangles: 11762,
    bytes: 447464,
    license: MESHY_LICENSE,
    placementHint: "Twin-Key Golem arena (variant 2) — torn-up quarry / construction site dressing.",
  },
  {
    id: "arena-sphinx-statue",
    url: "assets/meshy/arena/arena-sphinx-statue.glb",
    category: "arena",
    approxTriangles: 11656,
    bytes: 336224,
    license: MESHY_LICENSE,
    placementHint: "Sorted Sphinx arena (variant 5) — flanking museum-plaza statues.",
  },
  {
    id: "bld-alpine-lab",
    url: "assets/meshy/structure/bld-alpine-lab.glb",
    category: "structure",
    approxTriangles: 15634,
    bytes: 369988,
    license: MESHY_LICENSE,
    placementHint: "Mountain Outskirts lab, pairs with the lodge.",
  },
  {
    id: "bld-alpine-lodge",
    url: "assets/meshy/structure/bld-alpine-lodge.glb",
    category: "structure",
    approxTriangles: 17793,
    bytes: 361372,
    license: MESHY_LICENSE,
    placementHint: "Mountain Outskirts lodge / low residential.",
  },
  {
    id: "bld-brick-loft",
    url: "assets/meshy/structure/bld-brick-loft.glb",
    category: "structure",
    approxTriangles: 18573,
    bytes: 557956,
    license: MESHY_LICENSE,
    placementHint: "Old Town / Harborfront / Container Port elongated mid blocks.",
  },
  {
    id: "bld-corner-l",
    url: "assets/meshy/structure/bld-corner-l.glb",
    category: "structure",
    approxTriangles: 20952,
    bytes: 379452,
    license: MESHY_LICENSE,
    placementHint: "Generic corner-lot building for block corners.",
  },
  {
    id: "bld-glass-hq",
    url: "assets/meshy/structure/bld-glass-hq.glb",
    category: "structure",
    approxTriangles: 23438,
    bytes: 442320,
    license: MESHY_LICENSE,
    placementHint: "Verdant Downtown flagship HQ near the plaza.",
  },
  {
    id: "bld-glass-tower-a",
    url: "assets/meshy/structure/bld-glass-tower-a.glb",
    category: "structure",
    approxTriangles: 9521,
    bytes: 332672,
    license: MESHY_LICENSE,
    placementHint: "Verdant Downtown core towers; primary glass skyline.",
  },
  {
    id: "bld-glass-tower-b",
    url: "assets/meshy/structure/bld-glass-tower-b.glb",
    category: "structure",
    approxTriangles: 21086,
    bytes: 341508,
    license: MESHY_LICENSE,
    placementHint: "Verdant Downtown / Neon Quarter secondary glass towers.",
  },
  {
    id: "bld-harbor-civic",
    url: "assets/meshy/structure/bld-harbor-civic.glb",
    category: "structure",
    approxTriangles: 21612,
    bytes: 413480,
    license: MESHY_LICENSE,
    placementHint: "Harborfront civic anchor near the lighthouse.",
  },
  {
    id: "bld-harbor-warehouse",
    url: "assets/meshy/structure/bld-harbor-warehouse.glb",
    category: "structure",
    approxTriangles: 19199,
    bytes: 415136,
    license: MESHY_LICENSE,
    placementHint: "Harborfront working street walls.",
  },
  {
    id: "bld-midrise-balcony",
    url: "assets/meshy/structure/bld-midrise-balcony.glb",
    category: "structure",
    approxTriangles: 20451,
    bytes: 589132,
    license: MESHY_LICENSE,
    placementHint: "Residential street walls in any district; lived-in balcony texture the current set lacks.",
  },
  {
    id: "bld-midrise-deco-office",
    url: "assets/meshy/structure/bld-midrise-deco-office.glb",
    category: "structure",
    approxTriangles: 20345,
    bytes: 580768,
    license: MESHY_LICENSE,
    placementHint: "Old Town / Verdant Downtown boundary blocks; dressed-stone contrast to glass and brick.",
  },
  {
    id: "bld-midrise-mixed",
    url: "assets/meshy/structure/bld-midrise-mixed.glb",
    category: "structure",
    approxTriangles: 22881,
    bytes: 653524,
    license: MESHY_LICENSE,
    placementHint: "Main-street walls in every district; shop-below-homes-above texture.",
  },
  {
    id: "bld-neon-arcade",
    url: "assets/meshy/structure/bld-neon-arcade.glb",
    category: "structure",
    approxTriangles: 18005,
    bytes: 348352,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter arcade / entertainment corner.",
  },
  {
    id: "bld-neon-signage-a",
    url: "assets/meshy/structure/bld-neon-signage-a.glb",
    category: "structure",
    approxTriangles: 22897,
    bytes: 476920,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter signage-covered street walls.",
  },
  {
    id: "bld-neon-signage-b",
    url: "assets/meshy/structure/bld-neon-signage-b.glb",
    category: "structure",
    approxTriangles: 20986,
    bytes: 411204,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter secondary signage block.",
  },
  {
    id: "bld-neon-tower",
    url: "assets/meshy/structure/bld-neon-tower.glb",
    category: "structure",
    approxTriangles: 23381,
    bytes: 408264,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter skyline tower.",
  },
  {
    id: "bld-night-hotel",
    url: "assets/meshy/structure/bld-night-hotel.glb",
    category: "structure",
    approxTriangles: 20143,
    bytes: 534924,
    license: MESHY_LICENSE,
    placementHint: "Elongated mid-rise slots any district; warm hotel identity for the night city.",
  },
  {
    id: "bld-office-wide",
    url: "assets/meshy/structure/bld-office-wide.glb",
    category: "structure",
    approxTriangles: 20822,
    bytes: 673468,
    license: MESHY_LICENSE,
    placementHint: "Wide low mid-rise slots; fills the wide-box gap the square models refuse.",
  },
  {
    id: "bld-oldtown-brick-a",
    url: "assets/meshy/structure/bld-oldtown-brick-a.glb",
    category: "structure",
    approxTriangles: 21136,
    bytes: 426876,
    license: MESHY_LICENSE,
    placementHint: "Old Town brick street walls.",
  },
  {
    id: "bld-oldtown-brick-b",
    url: "assets/meshy/structure/bld-oldtown-brick-b.glb",
    category: "structure",
    approxTriangles: 21469,
    bytes: 434356,
    license: MESHY_LICENSE,
    placementHint: "Old Town heritage block, alternates with brick-a.",
  },
  {
    id: "bld-oldtown-clocktower",
    url: "assets/meshy/structure/bld-oldtown-clocktower.glb",
    category: "structure",
    approxTriangles: 24113,
    bytes: 427184,
    license: MESHY_LICENSE,
    placementHint: "Old Town civic landmark near the district gate.",
  },
  {
    id: "bld-port-block-a",
    url: "assets/meshy/structure/bld-port-block-a.glb",
    category: "structure",
    approxTriangles: 17956,
    bytes: 417296,
    license: MESHY_LICENSE,
    placementHint: "Container Port industrial street walls.",
  },
  {
    id: "bld-port-block-b",
    url: "assets/meshy/structure/bld-port-block-b.glb",
    category: "structure",
    approxTriangles: 18933,
    bytes: 402856,
    license: MESHY_LICENSE,
    placementHint: "Container Port warehouse, alternates with block-a.",
  },
  {
    id: "bld-row-house",
    url: "assets/meshy/structure/bld-row-house.glb",
    category: "structure",
    approxTriangles: 17077,
    bytes: 407760,
    license: MESHY_LICENSE,
    placementHint: "Generic narrow infill between wider blocks.",
  },
  {
    id: "bld-shop-arcade",
    url: "assets/meshy/storefront/bld-shop-arcade.glb",
    category: "storefront",
    approxTriangles: 13312,
    bytes: 443800,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter shopping streets; street-level unit slotted under mid-rise facades.",
  },
  {
    id: "bld-shop-noodle",
    url: "assets/meshy/storefront/bld-shop-noodle.glb",
    category: "storefront",
    approxTriangles: 14709,
    bytes: 483652,
    license: MESHY_LICENSE,
    placementHint: "Old Town lanes and Harborfront market edge; warm-glow eatery anchor, NPC vendor point.",
  },
  {
    id: "bld-shop-tech",
    url: "assets/meshy/storefront/bld-shop-tech.glb",
    category: "storefront",
    approxTriangles: 14526,
    bytes: 474596,
    license: MESHY_LICENSE,
    placementHint: "Verdant Downtown and Neon Quarter retail rows; cool-accent contrast to the noodle bar.",
  },
  {
    id: "bld-slab-tower",
    url: "assets/meshy/structure/bld-slab-tower.glb",
    category: "structure",
    approxTriangles: 20350,
    bytes: 392852,
    license: MESHY_LICENSE,
    placementHint: "Generic tall filler; any dense block.",
  },
  {
    id: "bld-spawn-atrium",
    url: "assets/meshy/structure/bld-spawn-atrium.glb",
    category: "structure",
    approxTriangles: 22838,
    bytes: 443188,
    license: MESHY_LICENSE,
    placementHint: "Spawn-street showpiece — replaces the most prominent primitive mid-rise near START_3D so new players see it on their first walk.",
  },
  {
    id: "bld-tower-blade",
    url: "assets/meshy/structure/bld-tower-blade.glb",
    category: "structure",
    approxTriangles: 18505,
    bytes: 380524,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter; knife-edge silhouette between the wider signage blocks.",
  },
  {
    id: "bld-tower-crown",
    url: "assets/meshy/structure/bld-tower-crown.glb",
    category: "structure",
    approxTriangles: 20966,
    bytes: 535676,
    license: MESHY_LICENSE,
    placementHint: "Verdant Downtown / Old Town boundary; warm-accent skyline counterpoint to the cyan glass towers.",
  },
  {
    id: "bld-tower-rect",
    url: "assets/meshy/structure/bld-tower-rect.glb",
    category: "structure",
    approxTriangles: 22374,
    bytes: 594508,
    license: MESHY_LICENSE,
    placementHint: "Non-square tower boxes every district; graphite counterpoint to the glass towers.",
  },
  {
    id: "bld-tower-terraced",
    url: "assets/meshy/structure/bld-tower-terraced.glb",
    category: "structure",
    approxTriangles: 21299,
    bytes: 626892,
    license: MESHY_LICENSE,
    placementHint: "Verdant Downtown green quarter; lime-accent tower, pairs with parks.",
  },
  {
    id: "bld-tower-twin",
    url: "assets/meshy/structure/bld-tower-twin.glb",
    category: "structure",
    approxTriangles: 23408,
    bytes: 478388,
    license: MESHY_LICENSE,
    placementHint: "Verdant Downtown plaza edge; distinctive gap silhouette against the skyline.",
  },
  {
    id: "character-boss-architect-attack",
    url: "assets/meshy/character/character-boss-architect-attack.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 56612,
    license: MESHY_LICENSE,
    placementHint: "Boss attack swing/cast one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-architect-death",
    url: "assets/meshy/character/character-boss-architect-death.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 53396,
    license: MESHY_LICENSE,
    placementHint: "Dying Backwards (action 189) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-architect-hit",
    url: "assets/meshy/character/character-boss-architect-hit.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 49128,
    license: MESHY_LICENSE,
    placementHint: "Hit Reaction (action 178) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-architect-idle",
    url: "assets/meshy/character/character-boss-architect-idle.glb",
    category: "character",
    approxTriangles: 28898,
    bytes: 680168,
    license: MESHY_LICENSE,
    placementHint: "ArchitectArena — replaces the procedural Architect3D primitives (final boss). Idle clip.",
  },
  {
    id: "character-boss-architect-run",
    url: "assets/meshy/character/character-boss-architect-run.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 28384,
    license: MESHY_LICENSE,
    placementHint: "Free rig Running clip; boss chase locomotion (animation-only GLB)",
  },
  {
    id: "character-boss-architect-scream",
    url: "assets/meshy/character/character-boss-architect-scream.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 87532,
    license: MESHY_LICENSE,
    placementHint: "Entrance roar/taunt one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-architect-slam",
    url: "assets/meshy/character/character-boss-architect-slam.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 53096,
    license: MESHY_LICENSE,
    placementHint: "Charged Ground Slam (action 127); the parryable force-slam heavy (animation-only GLB)",
  },
  {
    id: "character-boss-architect-stagger",
    url: "assets/meshy/character/character-boss-architect-stagger.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 64732,
    license: MESHY_LICENSE,
    placementHint: "Mummy Stagger (action 113); parry-punish reel loop (animation-only GLB)",
  },
  {
    id: "character-boss-architect-walk",
    url: "assets/meshy/character/character-boss-architect-walk.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 31784,
    license: MESHY_LICENSE,
    placementHint: "ArchitectArena — replaces the procedural Architect3D primitives (final boss). Walk clip.",
  },
  {
    id: "character-boss-beast-attack",
    url: "assets/meshy/character/character-boss-beast-attack.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 74852,
    license: MESHY_LICENSE,
    placementHint: "Boss attack swing/cast one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-beast-death",
    url: "assets/meshy/character/character-boss-beast-death.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 53552,
    license: MESHY_LICENSE,
    placementHint: "Dying Backwards (action 189) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-beast-hit",
    url: "assets/meshy/character/character-boss-beast-hit.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 74236,
    license: MESHY_LICENSE,
    placementHint: "Hit Reaction (action 178) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-beast-idle",
    url: "assets/meshy/character/character-boss-beast-idle.glb",
    category: "character",
    approxTriangles: 25081,
    bytes: 646520,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 4 (Stack City) — replaces the procedural claw beast. Idle clip.",
  },
  {
    id: "character-boss-beast-run",
    url: "assets/meshy/character/character-boss-beast-run.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 28112,
    license: MESHY_LICENSE,
    placementHint: "Free rig Running clip; boss chase locomotion (animation-only GLB)",
  },
  {
    id: "character-boss-beast-scream",
    url: "assets/meshy/character/character-boss-beast-scream.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 46720,
    license: MESHY_LICENSE,
    placementHint: "Entrance roar/taunt one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-beast-walk",
    url: "assets/meshy/character/character-boss-beast-walk.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 31844,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 4 (Stack City) — replaces the procedural claw beast. Walk clip.",
  },
  {
    id: "character-boss-gatekeeper-attack",
    url: "assets/meshy/character/character-boss-gatekeeper-attack.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 62396,
    license: MESHY_LICENSE,
    placementHint: "Boss attack swing/cast one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-gatekeeper-death",
    url: "assets/meshy/character/character-boss-gatekeeper-death.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 44848,
    license: MESHY_LICENSE,
    placementHint: "Dying Backwards (action 189) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-gatekeeper-hit",
    url: "assets/meshy/character/character-boss-gatekeeper-hit.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 37616,
    license: MESHY_LICENSE,
    placementHint: "Hit Reaction (action 178) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-gatekeeper-idle",
    url: "assets/meshy/character/character-boss-gatekeeper-idle.glb",
    category: "character",
    approxTriangles: 22541,
    bytes: 665372,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 3 (Twin Bridges) — replaces the procedural helm knight. Idle clip.",
  },
  {
    id: "character-boss-gatekeeper-run",
    url: "assets/meshy/character/character-boss-gatekeeper-run.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 28148,
    license: MESHY_LICENSE,
    placementHint: "Free rig Running clip; boss chase locomotion (animation-only GLB)",
  },
  {
    id: "character-boss-gatekeeper-scream",
    url: "assets/meshy/character/character-boss-gatekeeper-scream.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 66444,
    license: MESHY_LICENSE,
    placementHint: "Entrance roar/taunt one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-gatekeeper-walk",
    url: "assets/meshy/character/character-boss-gatekeeper-walk.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 31792,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 3 (Twin Bridges) — replaces the procedural helm knight. Walk clip.",
  },
  {
    id: "character-boss-golem-attack",
    url: "assets/meshy/character/character-boss-golem-attack.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 52816,
    license: MESHY_LICENSE,
    placementHint: "Boss attack swing/cast one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-golem-death",
    url: "assets/meshy/character/character-boss-golem-death.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 51720,
    license: MESHY_LICENSE,
    placementHint: "Dying Backwards (action 189) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-golem-hit",
    url: "assets/meshy/character/character-boss-golem-hit.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 34884,
    license: MESHY_LICENSE,
    placementHint: "Hit Reaction (action 178) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-golem-idle",
    url: "assets/meshy/character/character-boss-golem-idle.glb",
    category: "character",
    approxTriangles: 24727,
    bytes: 668636,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 2 (Memory Mines) — replaces the procedural block brute. Idle clip.",
  },
  {
    id: "character-boss-golem-run",
    url: "assets/meshy/character/character-boss-golem-run.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 28408,
    license: MESHY_LICENSE,
    placementHint: "Free rig Running clip; boss chase locomotion (animation-only GLB)",
  },
  {
    id: "character-boss-golem-scream",
    url: "assets/meshy/character/character-boss-golem-scream.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 35232,
    license: MESHY_LICENSE,
    placementHint: "Entrance roar/taunt one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-golem-walk",
    url: "assets/meshy/character/character-boss-golem-walk.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 31568,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 2 (Memory Mines) — replaces the procedural block brute. Walk clip.",
  },
  {
    id: "character-boss-hider-attack",
    url: "assets/meshy/character/character-boss-hider-attack.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 47544,
    license: MESHY_LICENSE,
    placementHint: "Boss attack swing/cast one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-hider-death",
    url: "assets/meshy/character/character-boss-hider-death.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 42476,
    license: MESHY_LICENSE,
    placementHint: "Dying Backwards (action 189) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-hider-hit",
    url: "assets/meshy/character/character-boss-hider-hit.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 63540,
    license: MESHY_LICENSE,
    placementHint: "Hit Reaction (action 178) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-hider-idle",
    url: "assets/meshy/character/character-boss-hider-idle.glb",
    category: "character",
    approxTriangles: 24752,
    bytes: 638120,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 0 (Scanner Valley) — replaces the procedural hooded villain. Idle clip.",
  },
  {
    id: "character-boss-hider-run",
    url: "assets/meshy/character/character-boss-hider-run.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 28144,
    license: MESHY_LICENSE,
    placementHint: "Free rig Running clip; boss chase locomotion (animation-only GLB)",
  },
  {
    id: "character-boss-hider-scream",
    url: "assets/meshy/character/character-boss-hider-scream.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 76956,
    license: MESHY_LICENSE,
    placementHint: "Entrance roar/taunt one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-hider-walk",
    url: "assets/meshy/character/character-boss-hider-walk.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 31736,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 0 (Scanner Valley) — replaces the procedural hooded villain. Walk clip.",
  },
  {
    id: "character-boss-mimic-attack",
    url: "assets/meshy/character/character-boss-mimic-attack.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 43308,
    license: MESHY_LICENSE,
    placementHint: "Boss attack swing/cast one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-mimic-death",
    url: "assets/meshy/character/character-boss-mimic-death.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 46600,
    license: MESHY_LICENSE,
    placementHint: "Dying Backwards (action 189) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-mimic-hit",
    url: "assets/meshy/character/character-boss-mimic-hit.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 38724,
    license: MESHY_LICENSE,
    placementHint: "Hit Reaction (action 178) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-mimic-idle",
    url: "assets/meshy/character/character-boss-mimic-idle.glb",
    category: "character",
    approxTriangles: 24705,
    bytes: 598428,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 1 (Letter Lagoon) — replaces the procedural visor duelist. Idle clip.",
  },
  {
    id: "character-boss-mimic-run",
    url: "assets/meshy/character/character-boss-mimic-run.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 28116,
    license: MESHY_LICENSE,
    placementHint: "Free rig Running clip; boss chase locomotion (animation-only GLB)",
  },
  {
    id: "character-boss-mimic-scream",
    url: "assets/meshy/character/character-boss-mimic-scream.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 60008,
    license: MESHY_LICENSE,
    placementHint: "Entrance roar/taunt one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-mimic-walk",
    url: "assets/meshy/character/character-boss-mimic-walk.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 31816,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 1 (Letter Lagoon) — replaces the procedural visor duelist. Walk clip.",
  },
  {
    id: "character-boss-sphinx-attack",
    url: "assets/meshy/character/character-boss-sphinx-attack.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 47788,
    license: MESHY_LICENSE,
    placementHint: "Boss attack swing/cast one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-sphinx-death",
    url: "assets/meshy/character/character-boss-sphinx-death.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 61532,
    license: MESHY_LICENSE,
    placementHint: "Dying Backwards (action 189) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-sphinx-hit",
    url: "assets/meshy/character/character-boss-sphinx-hit.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 48604,
    license: MESHY_LICENSE,
    placementHint: "Hit Reaction (action 178) one-shot (animation-only GLB)",
  },
  {
    id: "character-boss-sphinx-idle",
    url: "assets/meshy/character/character-boss-sphinx-idle.glb",
    category: "character",
    approxTriangles: 24688,
    bytes: 615748,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 5 (Halving Heights) — replaces the procedural pharaoh-mage. Idle clip.",
  },
  {
    id: "character-boss-sphinx-run",
    url: "assets/meshy/character/character-boss-sphinx-run.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 28228,
    license: MESHY_LICENSE,
    placementHint: "Free rig Running clip; boss chase locomotion (animation-only GLB)",
  },
  {
    id: "character-boss-sphinx-scream",
    url: "assets/meshy/character/character-boss-sphinx-scream.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 44520,
    license: MESHY_LICENSE,
    placementHint: "Entrance roar/taunt one-shot (animation-only GLB); action id in meshy-boss-clips.mjs",
  },
  {
    id: "character-boss-sphinx-walk",
    url: "assets/meshy/character/character-boss-sphinx-walk.glb",
    category: "character",
    approxTriangles: 0,
    bytes: 31788,
    license: MESHY_LICENSE,
    placementHint: "BossArena variant 5 (Halving Heights) — replaces the procedural pharaoh-mage. Walk clip.",
  },
  {
    id: "character-boss-vex-idle",
    url: "assets/meshy/character/character-boss-vex-idle.glb",
    category: "character",
    approxTriangles: 28228,
    bytes: 757668,
    license: MESHY_LICENSE,
    placementHint: "VexBoss3D replacement — the procedural primitive boss becomes a real model (idle/slam/scream clips). Idle clip.",
  },
  {
    id: "character-boss-vex-slam",
    url: "assets/meshy/character/character-boss-vex-slam.glb",
    category: "character",
    approxTriangles: 28228,
    bytes: 750656,
    license: MESHY_LICENSE,
    placementHint: "Charged Ground Slam (action 127); boss AoE attack telegraph+strike",
  },
  {
    id: "character-boss-vex-walk",
    url: "assets/meshy/character/character-boss-vex-walk.glb",
    category: "character",
    approxTriangles: 28228,
    bytes: 730288,
    license: MESHY_LICENSE,
    placementHint: "VexBoss3D replacement — the procedural primitive boss becomes a real model (idle/slam/scream clips). Walk clip.",
  },
  {
    id: "character-citizen-business-idle",
    url: "assets/meshy/character/character-citizen-business-idle.glb",
    category: "character",
    approxTriangles: 18627,
    bytes: 307848,
    license: MESHY_LICENSE,
    placementHint: "NpcCitizen pool — business district pedestrian (walk + idle clips). Idle clip.",
  },
  {
    id: "character-citizen-business-walk",
    url: "assets/meshy/character/character-citizen-business-walk.glb",
    category: "character",
    approxTriangles: 18627,
    bytes: 280488,
    license: MESHY_LICENSE,
    placementHint: "NpcCitizen pool — business district pedestrian (walk + idle clips). Walk clip.",
  },
  {
    id: "character-citizen-hoodie-idle",
    url: "assets/meshy/character/character-citizen-hoodie-idle.glb",
    category: "character",
    approxTriangles: 18609,
    bytes: 331352,
    license: MESHY_LICENSE,
    placementHint: "NpcCitizen pool — arcade and plaza pedestrian (walk + idle clips). Idle clip.",
  },
  {
    id: "character-citizen-hoodie-walk",
    url: "assets/meshy/character/character-citizen-hoodie-walk.glb",
    category: "character",
    approxTriangles: 18609,
    bytes: 304716,
    license: MESHY_LICENSE,
    placementHint: "NpcCitizen pool — arcade and plaza pedestrian (walk + idle clips). Walk clip.",
  },
  {
    id: "character-citizen-idle",
    url: "assets/meshy/character/character-citizen-idle.glb",
    category: "character",
    approxTriangles: 20671,
    bytes: 455548,
    license: MESHY_LICENSE,
    placementHint: "Experimental Meshy-rigged pedestrian (walk + idle clips); NOT wired into CitizenCrowd yet. Idle clip.",
  },
  {
    id: "character-citizen-walk",
    url: "assets/meshy/character/character-citizen-walk.glb",
    category: "character",
    approxTriangles: 20671,
    bytes: 427920,
    license: MESHY_LICENSE,
    placementHint: "Experimental Meshy-rigged pedestrian (walk + idle clips); NOT wired into CitizenCrowd yet. Walk clip.",
  },
  {
    id: "character-citizen-worker-idle",
    url: "assets/meshy/character/character-citizen-worker-idle.glb",
    category: "character",
    approxTriangles: 18736,
    bytes: 338220,
    license: MESHY_LICENSE,
    placementHint: "NpcCitizen pool — port and construction zones (walk + idle clips). Idle clip.",
  },
  {
    id: "character-citizen-worker-walk",
    url: "assets/meshy/character/character-citizen-worker-walk.glb",
    category: "character",
    approxTriangles: 18736,
    bytes: 310324,
    license: MESHY_LICENSE,
    placementHint: "NpcCitizen pool — port and construction zones (walk + idle clips). Walk clip.",
  },
  {
    id: "character-civ-elder-cower",
    url: "assets/meshy/character/character-civ-elder-cower.glb",
    category: "character",
    approxTriangles: 18520,
    bytes: 530376,
    license: MESHY_LICENSE,
    placementHint: "CrouchLookAroundBow (action 258); rescue-wait cower loop",
  },
  {
    id: "character-civ-elder-idle",
    url: "assets/meshy/character/character-civ-elder-idle.glb",
    category: "character",
    approxTriangles: 18520,
    bytes: 527028,
    license: MESHY_LICENSE,
    placementHint: "Rescue-mission civilian B — smallest, most vulnerable silhouette in the city (cower/relieved clips). Idle clip.",
  },
  {
    id: "character-civ-elder-relieved",
    url: "assets/meshy/character/character-civ-elder-relieved.glb",
    category: "character",
    approxTriangles: 18520,
    bytes: 508512,
    license: MESHY_LICENSE,
    placementHint: "Cheer with Both Hands Up (action 298); rescued celebrate one-shot",
  },
  {
    id: "character-civ-elder-walk",
    url: "assets/meshy/character/character-civ-elder-walk.glb",
    category: "character",
    approxTriangles: 18520,
    bytes: 499612,
    license: MESHY_LICENSE,
    placementHint: "Rescue-mission civilian B — smallest, most vulnerable silhouette in the city (cower/relieved clips). Walk clip.",
  },
  {
    id: "character-civ-vendor-cower",
    url: "assets/meshy/character/character-civ-vendor-cower.glb",
    category: "character",
    approxTriangles: 18621,
    bytes: 536924,
    license: MESHY_LICENSE,
    placementHint: "CrouchLookAroundBow (action 258); rescue-wait cower loop",
  },
  {
    id: "character-civ-vendor-idle",
    url: "assets/meshy/character/character-civ-vendor-idle.glb",
    category: "character",
    approxTriangles: 18621,
    bytes: 534528,
    license: MESHY_LICENSE,
    placementHint: "Rescue-mission civilian A — warm silhouette, reads instantly non-hostile (cower/relieved clips). Idle clip.",
  },
  {
    id: "character-civ-vendor-relieved",
    url: "assets/meshy/character/character-civ-vendor-relieved.glb",
    category: "character",
    approxTriangles: 18621,
    bytes: 515944,
    license: MESHY_LICENSE,
    placementHint: "Cheer with Both Hands Up (action 298); rescued celebrate one-shot",
  },
  {
    id: "character-civ-vendor-walk",
    url: "assets/meshy/character/character-civ-vendor-walk.glb",
    category: "character",
    approxTriangles: 18621,
    bytes: 506352,
    license: MESHY_LICENSE,
    placementHint: "Rescue-mission civilian A — warm silhouette, reads instantly non-hostile (cower/relieved clips). Walk clip.",
  },
  {
    id: "character-hero-a-crouch",
    url: "assets/meshy/character/character-hero-a-crouch.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 410320,
    license: MESHY_LICENSE,
    placementHint: "Cautious Crouch Walk Forward (in-place, action 616); C lay-low state",
  },
  {
    id: "character-hero-a-dash",
    url: "assets/meshy/character/character-hero-a-dash.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 417208,
    license: MESHY_LICENSE,
    placementHint: "Roll Dodge (action 158); Q blade-dash lunge",
  },
  {
    id: "character-hero-a-hit",
    url: "assets/meshy/character/character-hero-a-hit.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 415592,
    license: MESHY_LICENSE,
    placementHint: "Hit Reaction (action 178); damage feedback",
  },
  {
    id: "character-hero-a-idle",
    url: "assets/meshy/character/character-hero-a-idle.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 436976,
    license: MESHY_LICENSE,
    placementHint: "Player avatar variant A — replaces Soldier.glb via ThirdPersonController clip set. Idle clip.",
  },
  {
    id: "character-hero-a-jump",
    url: "assets/meshy/character/character-hero-a-jump.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 418384,
    license: MESHY_LICENSE,
    placementHint: "Regular Jump (action 466); Space jump state",
  },
  {
    id: "character-hero-a-run",
    url: "assets/meshy/character/character-hero-a-run.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 405704,
    license: MESHY_LICENSE,
    placementHint: "Running — free rig-task clip; controller run state",
  },
  {
    id: "character-hero-a-shoot",
    url: "assets/meshy/character/character-hero-a-shoot.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 428868,
    license: MESHY_LICENSE,
    placementHint: "Walk Forward While Shooting (in-place, action 690); F fire state",
  },
  {
    id: "character-hero-a-slash",
    url: "assets/meshy/character/character-hero-a-slash.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 413988,
    license: MESHY_LICENSE,
    placementHint: "Right-hand Sword Slash (action 219); blade-dash swing layer",
  },
  {
    id: "character-hero-a-sprint",
    url: "assets/meshy/character/character-hero-a-sprint.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 405156,
    license: MESHY_LICENSE,
    placementHint: "Lean Forward Sprint (in-place, action 644); Shift sprint state",
  },
  {
    id: "character-hero-a-victory",
    url: "assets/meshy/character/character-hero-a-victory.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 479788,
    license: MESHY_LICENSE,
    placementHint: "Victory Cheer (action 59); quest-clear celebrate",
  },
  {
    id: "character-hero-a-walk",
    url: "assets/meshy/character/character-hero-a-walk.glb",
    category: "character",
    approxTriangles: 28999,
    bytes: 409756,
    license: MESHY_LICENSE,
    placementHint: "Player avatar variant A — replaces Soldier.glb via ThirdPersonController clip set. Walk clip.",
  },
  {
    id: "character-hero-b-crouch",
    url: "assets/meshy/character/character-hero-b-crouch.glb",
    category: "character",
    approxTriangles: 28802,
    bytes: 443536,
    license: MESHY_LICENSE,
    placementHint: "Cautious Crouch Walk Forward (in-place, action 616); C lay-low state",
  },
  {
    id: "character-hero-b-dash",
    url: "assets/meshy/character/character-hero-b-dash.glb",
    category: "character",
    approxTriangles: 28802,
    bytes: 450336,
    license: MESHY_LICENSE,
    placementHint: "Roll Dodge (action 158); Q blade-dash lunge",
  },
  {
    id: "character-hero-b-idle",
    url: "assets/meshy/character/character-hero-b-idle.glb",
    category: "character",
    approxTriangles: 28802,
    bytes: 468792,
    license: MESHY_LICENSE,
    placementHint: "Player avatar variant B — replaces Soldier.glb via ThirdPersonController clip set. Idle clip.",
  },
  {
    id: "character-hero-b-jump",
    url: "assets/meshy/character/character-hero-b-jump.glb",
    category: "character",
    approxTriangles: 28802,
    bytes: 451628,
    license: MESHY_LICENSE,
    placementHint: "Regular Jump (action 466); Space jump state",
  },
  {
    id: "character-hero-b-run",
    url: "assets/meshy/character/character-hero-b-run.glb",
    category: "character",
    approxTriangles: 28802,
    bytes: 438576,
    license: MESHY_LICENSE,
    placementHint: "Running — free rig-task clip; controller run state",
  },
  {
    id: "character-hero-b-shoot",
    url: "assets/meshy/character/character-hero-b-shoot.glb",
    category: "character",
    approxTriangles: 28802,
    bytes: 461880,
    license: MESHY_LICENSE,
    placementHint: "Walk Forward While Shooting (in-place, action 690); F fire state",
  },
  {
    id: "character-hero-b-sprint",
    url: "assets/meshy/character/character-hero-b-sprint.glb",
    category: "character",
    approxTriangles: 28802,
    bytes: 438100,
    license: MESHY_LICENSE,
    placementHint: "Lean Forward Sprint (in-place, action 644); Shift sprint state",
  },
  {
    id: "character-hero-b-walk",
    url: "assets/meshy/character/character-hero-b-walk.glb",
    category: "character",
    approxTriangles: 28802,
    bytes: 441960,
    license: MESHY_LICENSE,
    placementHint: "Player avatar variant B — replaces Soldier.glb via ThirdPersonController clip set. Walk clip.",
  },
  {
    id: "character-zombie-android-attack",
    url: "assets/meshy/character/character-zombie-android-attack.glb",
    category: "character",
    approxTriangles: 20418,
    bytes: 361192,
    license: MESHY_LICENSE,
    placementHint: "Punch Forward with Both Fists (action 214); contact attack / Punch",
  },
  {
    id: "character-zombie-android-idle",
    url: "assets/meshy/character/character-zombie-android-idle.glb",
    category: "character",
    approxTriangles: 20418,
    bytes: 365576,
    license: MESHY_LICENSE,
    placementHint: "ZombieHorde replacement A — corrupted android (walk/run/attack clips). Idle clip.",
  },
  {
    id: "character-zombie-android-shamble",
    url: "assets/meshy/character/character-zombie-android-shamble.glb",
    category: "character",
    approxTriangles: 20418,
    bytes: 364656,
    license: MESHY_LICENSE,
    placementHint: "Frankenstein/Monster Walk (action 112); menacing horde gait",
  },
  {
    id: "character-zombie-android-walk",
    url: "assets/meshy/character/character-zombie-android-walk.glb",
    category: "character",
    approxTriangles: 20418,
    bytes: 338508,
    license: MESHY_LICENSE,
    placementHint: "ZombieHorde replacement A — corrupted android (walk/run/attack clips). Walk clip.",
  },
  {
    id: "character-zombie-flesh-attack",
    url: "assets/meshy/character/character-zombie-flesh-attack.glb",
    category: "character",
    approxTriangles: 20695,
    bytes: 532360,
    license: MESHY_LICENSE,
    placementHint: "Punch Forward with Both Fists (action 214); contact attack / Punch",
  },
  {
    id: "character-zombie-flesh-idle",
    url: "assets/meshy/character/character-zombie-flesh-idle.glb",
    category: "character",
    approxTriangles: 20695,
    bytes: 536660,
    license: MESHY_LICENSE,
    placementHint: "ZombieHorde rig A — organic shambler (replaces zombie-android). Idle clip.",
  },
  {
    id: "character-zombie-flesh-shamble",
    url: "assets/meshy/character/character-zombie-flesh-shamble.glb",
    category: "character",
    approxTriangles: 20695,
    bytes: 535648,
    license: MESHY_LICENSE,
    placementHint: "Frankenstein/Monster Walk (action 112); undead horde gait",
  },
  {
    id: "character-zombie-flesh-walk",
    url: "assets/meshy/character/character-zombie-flesh-walk.glb",
    category: "character",
    approxTriangles: 20695,
    bytes: 509624,
    license: MESHY_LICENSE,
    placementHint: "ZombieHorde rig A — organic shambler (replaces zombie-android). Walk clip.",
  },
  {
    id: "character-zombie-hulk-attack",
    url: "assets/meshy/character/character-zombie-hulk-attack.glb",
    category: "character",
    approxTriangles: 20695,
    bytes: 537764,
    license: MESHY_LICENSE,
    placementHint: "Punch Forward with Both Fists (action 214); contact attack / Punch",
  },
  {
    id: "character-zombie-hulk-idle",
    url: "assets/meshy/character/character-zombie-hulk-idle.glb",
    category: "character",
    approxTriangles: 20695,
    bytes: 542780,
    license: MESHY_LICENSE,
    placementHint: "ZombieHorde rig B — organic brute (replaces zombie-secbot). Idle clip.",
  },
  {
    id: "character-zombie-hulk-shamble",
    url: "assets/meshy/character/character-zombie-hulk-shamble.glb",
    category: "character",
    approxTriangles: 20695,
    bytes: 531608,
    license: MESHY_LICENSE,
    placementHint: "Unsteady Walk (action 123); heavy brute gait",
  },
  {
    id: "character-zombie-hulk-walk",
    url: "assets/meshy/character/character-zombie-hulk-walk.glb",
    category: "character",
    approxTriangles: 20695,
    bytes: 514644,
    license: MESHY_LICENSE,
    placementHint: "ZombieHorde rig B — organic brute (replaces zombie-secbot). Walk clip.",
  },
  {
    id: "character-zombie-secbot-attack",
    url: "assets/meshy/character/character-zombie-secbot-attack.glb",
    category: "character",
    approxTriangles: 19975,
    bytes: 371260,
    license: MESHY_LICENSE,
    placementHint: "Punch Forward with Both Fists (action 214); contact attack / Punch",
  },
  {
    id: "character-zombie-secbot-idle",
    url: "assets/meshy/character/character-zombie-secbot-idle.glb",
    category: "character",
    approxTriangles: 19975,
    bytes: 375744,
    license: MESHY_LICENSE,
    placementHint: "ZombieHorde replacement B — security robot (walk/run/attack clips). Idle clip.",
  },
  {
    id: "character-zombie-secbot-shamble",
    url: "assets/meshy/character/character-zombie-secbot-shamble.glb",
    category: "character",
    approxTriangles: 19975,
    bytes: 365996,
    license: MESHY_LICENSE,
    placementHint: "Unsteady Walk (action 123); glitching horde gait",
  },
  {
    id: "character-zombie-secbot-walk",
    url: "assets/meshy/character/character-zombie-secbot-walk.glb",
    category: "character",
    approxTriangles: 19975,
    bytes: 348704,
    license: MESHY_LICENSE,
    placementHint: "ZombieHorde replacement B — security robot (walk/run/attack clips). Walk clip.",
  },
  {
    id: "dojo-brass-orrery",
    url: "assets/meshy/dojo/dojo-brass-orrery.glb",
    category: "dojo",
    approxTriangles: 14079,
    bytes: 590528,
    license: MESHY_LICENSE,
    placementHint: "Orrery exhibit centerpiece (recursion wing).",
  },
  {
    id: "dojo-conveyor-unit",
    url: "assets/meshy/dojo/dojo-conveyor-unit.glb",
    category: "dojo",
    approxTriangles: 10820,
    bytes: 635520,
    license: MESHY_LICENSE,
    placementHint: "Dojo queue/stack exhibits (StackElevator, NodeTrainCars wings).",
  },
  {
    id: "dojo-crane-gantry",
    url: "assets/meshy/dojo/dojo-crane-gantry.glb",
    category: "dojo",
    approxTriangles: 14011,
    bytes: 803020,
    license: MESHY_LICENSE,
    placementHint: "HeapCrane exhibit and Container Port skyline dressing.",
  },
  {
    id: "dojo-display-plinth",
    url: "assets/meshy/dojo/dojo-display-plinth.glb",
    category: "dojo",
    approxTriangles: 2372,
    bytes: 370332,
    license: MESHY_LICENSE,
    placementHint: "Generic exhibit pedestal across all dojo wings.",
  },
  {
    id: "dojo-holo-console",
    url: "assets/meshy/dojo/dojo-holo-console.glb",
    category: "dojo",
    approxTriangles: 8562,
    bytes: 543968,
    license: MESHY_LICENSE,
    placementHint: "Dojo exhibit control points; boss arena hacking stations.",
  },
  {
    id: "dojo-server-rack",
    url: "assets/meshy/dojo/dojo-server-rack.glb",
    category: "dojo",
    approxTriangles: 8346,
    bytes: 576228,
    license: MESHY_LICENSE,
    placementHint: "HashLockers wing walls and Memory Mines dressing.",
  },
  {
    id: "dojo-switchboard-panel",
    url: "assets/meshy/dojo/dojo-switchboard-panel.glb",
    category: "dojo",
    approxTriangles: 6244,
    bytes: 644092,
    license: MESHY_LICENSE,
    placementHint: "BitSwitchboard and DepartureBoard exhibit dressing.",
  },
  {
    id: "dojo-vault-door",
    url: "assets/meshy/dojo/dojo-vault-door.glb",
    category: "dojo",
    approxTriangles: 14280,
    bytes: 716100,
    license: MESHY_LICENSE,
    placementHint: "Hash Lockers exhibit entrance; SearchVault wing door.",
  },
  {
    id: "dojo-workbench",
    url: "assets/meshy/dojo/dojo-workbench.glb",
    category: "dojo",
    approxTriangles: 11315,
    bytes: 691480,
    license: MESHY_LICENSE,
    placementHint: "Dojo maker wing and Container Port garages.",
  },
  {
    id: "interact-arcade-cabinet",
    url: "assets/meshy/interact/interact-arcade-cabinet.glb",
    category: "interact",
    approxTriangles: 8863,
    bytes: 571120,
    license: MESHY_LICENSE,
    placementHint: "Arcade minigame stations (ArcadeCabinet interactable).",
  },
  {
    id: "interact-camera-tripod",
    url: "assets/meshy/interact/interact-camera-tripod.glb",
    category: "interact",
    approxTriangles: 8194,
    bytes: 554716,
    license: MESHY_LICENSE,
    placementHint: "Photo spot markers (PhotoSpot interactable).",
  },
  {
    id: "interact-memory-crystal",
    url: "assets/meshy/interact/interact-memory-crystal.glb",
    category: "interact",
    approxTriangles: 4552,
    bytes: 534880,
    license: MESHY_LICENSE,
    placementHint: "Memory Crystal collectibles (MemoryCrystals interactable).",
  },
  {
    id: "interact-parcel-box",
    url: "assets/meshy/interact/interact-parcel-box.glb",
    category: "interact",
    approxTriangles: 3362,
    bytes: 491060,
    license: MESHY_LICENSE,
    placementHint: "Courier quest pickups (CourierBeacon interactable).",
  },
  {
    id: "landmark-bridge-pylon",
    url: "assets/meshy/landmark/landmark-bridge-pylon.glb",
    category: "landmark",
    approxTriangles: 28986,
    bytes: 791352,
    license: MESHY_LICENSE,
    placementHint: "Harborfront (realm2) waterfront — Twin Bridges echo across the lagoon.",
  },
  {
    id: "landmark-district-gate",
    url: "assets/meshy/landmark/landmark-district-gate.glb",
    category: "landmark",
    approxTriangles: 29398,
    bytes: 895356,
    license: MESHY_LICENSE,
    placementHint: "Old Town (realm4) main street threshold.",
  },
  {
    id: "landmark-lighthouse",
    url: "assets/meshy/landmark/landmark-lighthouse.glb",
    category: "landmark",
    approxTriangles: 28388,
    bytes: 828924,
    license: MESHY_LICENSE,
    placementHint: "Container Port (realm5) breakwater point.",
  },
  {
    id: "landmark-observatory-dome",
    url: "assets/meshy/landmark/landmark-observatory-dome.glb",
    category: "landmark",
    approxTriangles: 30001,
    bytes: 897164,
    license: MESHY_LICENSE,
    placementHint: "Verdant Downtown (realm1) hill — Scanner Valley sightline anchor.",
  },
  {
    id: "landmark-signal-spire",
    url: "assets/meshy/landmark/landmark-signal-spire.glb",
    category: "landmark",
    approxTriangles: 31112,
    bytes: 1215984,
    license: MESHY_LICENSE,
    placementHint: "City-center high ground — visible from every district; the skyline pin the spiral tower orbits around.",
  },
  {
    id: "landmark-spiral-tower",
    url: "assets/meshy/landmark/landmark-spiral-tower.glb",
    category: "landmark",
    approxTriangles: 35968,
    bytes: 892760,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter (realm3) skyline centerpiece.",
  },
  {
    id: "landmark-wind-turbine",
    url: "assets/meshy/landmark/landmark-wind-turbine.glb",
    category: "landmark",
    approxTriangles: 23769,
    bytes: 572360,
    license: MESHY_LICENSE,
    placementHint: "Mountain Outskirts (realm6) ridge line; slow blade spin in-scene.",
  },
  {
    id: "nature-bush-large",
    url: "assets/meshy/nature/nature-bush-large.glb",
    category: "nature",
    approxTriangles: 2967,
    bytes: 192836,
    license: MESHY_LICENSE,
    placementHint: "Fills planting beds and building foundations; pairs with trees.",
  },
  {
    id: "nature-data-palm",
    url: "assets/meshy/nature/nature-data-palm.glb",
    category: "nature",
    approxTriangles: 11393,
    bytes: 612776,
    license: MESHY_LICENSE,
    placementHint: "Harborfront promenade and Crystal Neon Quarter boulevards.",
  },
  {
    id: "nature-hedge-low",
    url: "assets/meshy/nature/nature-hedge-low.glb",
    category: "nature",
    approxTriangles: 5044,
    bytes: 208236,
    license: MESHY_LICENSE,
    placementHint: "Path borders and plaza planters; tiles end-to-end, lower than nature-hedge-section.",
  },
  {
    id: "nature-hedge-section",
    url: "assets/meshy/nature/nature-hedge-section.glb",
    category: "nature",
    approxTriangles: 6907,
    bytes: 658624,
    license: MESHY_LICENSE,
    placementHint: "Modular garden walls; tile end-to-end along paths.",
  },
  {
    id: "nature-rock-cluster",
    url: "assets/meshy/nature/nature-rock-cluster.glb",
    category: "nature",
    approxTriangles: 5143,
    bytes: 654900,
    license: MESHY_LICENSE,
    placementHint: "Mountain Outskirts slopes and park landscaping.",
  },
  {
    id: "nature-tree-broadleaf",
    url: "assets/meshy/nature/nature-tree-broadleaf.glb",
    category: "nature",
    approxTriangles: 11525,
    bytes: 755264,
    license: MESHY_LICENSE,
    placementHint: "Park strips and plaza greens city-wide.",
  },
  {
    id: "nature-tree-cypress",
    url: "assets/meshy/nature/nature-tree-cypress.glb",
    category: "nature",
    approxTriangles: 5920,
    bytes: 239796,
    license: MESHY_LICENSE,
    placementHint: "Formal rows along plaza edges and driveways; vertical rhythm element.",
  },
  {
    id: "nature-tree-dead",
    url: "assets/meshy/nature/nature-tree-dead.glb",
    category: "nature",
    approxTriangles: 8021,
    bytes: 259400,
    license: MESHY_LICENSE,
    placementHint: "Mountain Outskirts ridges and boss-arena approaches; mood dressing.",
  },
  {
    id: "nature-tree-maple",
    url: "assets/meshy/nature/nature-tree-maple.glb",
    category: "nature",
    approxTriangles: 9712,
    bytes: 291696,
    license: MESHY_LICENSE,
    placementHint: "Old Town and Verdant Downtown accent tree; autumn color contrast.",
  },
  {
    id: "nature-tree-oak",
    url: "assets/meshy/nature/nature-tree-oak.glb",
    category: "nature",
    approxTriangles: 10038,
    bytes: 307464,
    license: MESHY_LICENSE,
    placementHint: "Primary park and boulevard tree; scatter city-wide, scale 0.9-1.3.",
  },
  {
    id: "rooftop-antenna-cluster",
    url: "assets/meshy/rooftop/rooftop-antenna-cluster.glb",
    category: "rooftop",
    approxTriangles: 5998,
    bytes: 269908,
    license: MESHY_LICENSE,
    placementHint: "Tallest rooftop of each block; pairs with HVAC units.",
  },
  {
    id: "rooftop-hvac",
    url: "assets/meshy/rooftop/rooftop-hvac.glb",
    category: "rooftop",
    approxTriangles: 6073,
    bytes: 255528,
    license: MESHY_LICENSE,
    placementHint: "Every 2nd-3rd rooftop; clusters of 1-3 with vent pipes.",
  },
  {
    id: "rooftop-pergola",
    url: "assets/meshy/rooftop/rooftop-pergola.glb",
    category: "rooftop",
    approxTriangles: 6950,
    bytes: 285496,
    license: MESHY_LICENSE,
    placementHint: "Residential rooftops and cafe terraces; social spot dressing.",
  },
  {
    id: "rooftop-solar-array",
    url: "assets/meshy/rooftop/rooftop-solar-array.glb",
    category: "rooftop",
    approxTriangles: 5376,
    bytes: 227224,
    license: MESHY_LICENSE,
    placementHint: "Modern flat rooftops; angled toward the sun path.",
  },
  {
    id: "rooftop-vent-pipes",
    url: "assets/meshy/rooftop/rooftop-vent-pipes.glb",
    category: "rooftop",
    approxTriangles: 3804,
    bytes: 226428,
    license: MESHY_LICENSE,
    placementHint: "Scatter 2-4 per rooftop between larger kit pieces.",
  },
  {
    id: "rooftop-water-tower",
    url: "assets/meshy/rooftop/rooftop-water-tower.glb",
    category: "rooftop",
    approxTriangles: 9159,
    bytes: 279980,
    license: MESHY_LICENSE,
    placementHint: "Old Town and brick mid-rise rooftops; skyline silhouette anchor.",
  },
  {
    id: "storefront-awning",
    url: "assets/meshy/storefront/storefront-awning.glb",
    category: "storefront",
    approxTriangles: 5004,
    bytes: 215308,
    license: MESHY_LICENSE,
    placementHint: "Mounts over shop doors and windows on street-level facades.",
  },
  {
    id: "storefront-sign-blade",
    url: "assets/meshy/storefront/storefront-sign-blade.glb",
    category: "storefront",
    approxTriangles: 1780,
    bytes: 214384,
    license: MESHY_LICENSE,
    placementHint: "Projects from facades in Crystal Neon Quarter and Old Town shopping streets.",
  },
  {
    id: "storefront-sign-box",
    url: "assets/meshy/storefront/storefront-sign-box.glb",
    category: "storefront",
    approxTriangles: 1637,
    bytes: 84992,
    license: MESHY_LICENSE,
    placementHint: "Sits above shop entrances on every retail facade.",
  },
  {
    id: "street-barrier-crowd",
    url: "assets/meshy/street/street-barrier-crowd.glb",
    category: "street",
    approxTriangles: 3594,
    bytes: 238736,
    license: MESHY_LICENSE,
    placementHint: "Event frontages and road works; lighter movable sibling of street-jersey-barrier, tiles end-to-end.",
  },
  {
    id: "street-bench-ad",
    url: "assets/meshy/street/street-bench-ad.glb",
    category: "street",
    approxTriangles: 4972,
    bytes: 228444,
    license: MESHY_LICENSE,
    placementHint: "Bus stops without shelters; ad panel glows softly at night.",
  },
  {
    id: "street-bench-classic",
    url: "assets/meshy/street/street-bench-classic.glb",
    category: "street",
    approxTriangles: 7265,
    bytes: 658800,
    license: MESHY_LICENSE,
    placementHint: "Old Town (realm4) arcades and Mountain Outskirts (realm6) lookouts.",
  },
  {
    id: "street-bench-modern",
    url: "assets/meshy/street/street-bench-modern.glb",
    category: "street",
    approxTriangles: 5745,
    bytes: 608036,
    license: MESHY_LICENSE,
    placementHint: "Sidewalks and plaza edges in every district; pairs with planters.",
  },
  {
    id: "street-bench-neon",
    url: "assets/meshy/street/street-bench-neon.glb",
    category: "street",
    approxTriangles: 4401,
    bytes: 157552,
    license: MESHY_LICENSE,
    placementHint: "Plazas and metro entrances; third bench silhouette, reads futuristic next to the wrought classic.",
  },
  {
    id: "street-bike-rack",
    url: "assets/meshy/street/street-bike-rack.glb",
    category: "street",
    approxTriangles: 5040,
    bytes: 181796,
    license: MESHY_LICENSE,
    placementHint: "Near dojo entrances, metro canopies and plazas.",
  },
  {
    id: "street-billboard-holo",
    url: "assets/meshy/street/street-billboard-holo.glb",
    category: "street",
    approxTriangles: 8832,
    bytes: 258604,
    license: MESHY_LICENSE,
    placementHint: "Plaza edges and highway approaches; night-light anchor.",
  },
  {
    id: "street-billboard-wall",
    url: "assets/meshy/street/street-billboard-wall.glb",
    category: "street",
    approxTriangles: 6954,
    bytes: 283564,
    license: MESHY_LICENSE,
    placementHint: "Mid-rise facades in dense districts; angled toward streets.",
  },
  {
    id: "street-bollard",
    url: "assets/meshy/street/street-bollard.glb",
    category: "street",
    approxTriangles: 2307,
    bytes: 392216,
    license: MESHY_LICENSE,
    placementHint: "Rows of 3-5 sealing pedestrian plazas from hover lanes.",
  },
  {
    id: "street-bus-shelter",
    url: "assets/meshy/street/street-bus-shelter.glb",
    category: "street",
    approxTriangles: 9535,
    bytes: 715272,
    license: MESHY_LICENSE,
    placementHint: "One per district main street, faces the road lane.",
  },
  {
    id: "street-bus-shelter-old",
    url: "assets/meshy/street/street-bus-shelter-old.glb",
    category: "street",
    approxTriangles: 9752,
    bytes: 679268,
    license: MESHY_LICENSE,
    placementHint: "Old Town and Container Port stops; weathered counterpart to street-bus-shelter.",
  },
  {
    id: "street-dumpster",
    url: "assets/meshy/street/street-dumpster.glb",
    category: "street",
    approxTriangles: 6522,
    bytes: 230812,
    license: MESHY_LICENSE,
    placementHint: "Alleys and service yards; collision prop, pairs with scaffolding.",
  },
  {
    id: "street-fence-chainlink",
    url: "assets/meshy/street/street-fence-chainlink.glb",
    category: "street",
    approxTriangles: 3135,
    bytes: 174812,
    license: MESHY_LICENSE,
    placementHint: "Construction lots and Container Port perimeters; tiles end-to-end.",
  },
  {
    id: "street-fire-hydrant",
    url: "assets/meshy/street/street-fire-hydrant.glb",
    category: "street",
    approxTriangles: 5053,
    bytes: 580604,
    license: MESHY_LICENSE,
    placementHint: "Curbside every other block; collision prop.",
  },
  {
    id: "street-food-cart",
    url: "assets/meshy/street/street-food-cart.glb",
    category: "street",
    approxTriangles: 13476,
    bytes: 765384,
    license: MESHY_LICENSE,
    placementHint: "Harborfront pier and plaza corners; NPC vendor anchor point.",
  },
  {
    id: "street-holo-kiosk",
    url: "assets/meshy/street/street-holo-kiosk.glb",
    category: "street",
    approxTriangles: 8921,
    bytes: 573728,
    license: MESHY_LICENSE,
    placementHint: "Plaza corners and quest-board points; Crystal Neon Quarter density 2×.",
  },
  {
    id: "street-hydrant-modern",
    url: "assets/meshy/street/street-hydrant-modern.glb",
    category: "street",
    approxTriangles: 4084,
    bytes: 217904,
    license: MESHY_LICENSE,
    placementHint: "Curbside variant B; alternates blocks with street-fire-hydrant.",
  },
  {
    id: "street-jersey-barrier",
    url: "assets/meshy/street/street-jersey-barrier.glb",
    category: "street",
    approxTriangles: 702,
    bytes: 180420,
    license: MESHY_LICENSE,
    placementHint: "Road works and arena approaches; tiles end-to-end, collision prop.",
  },
  {
    id: "street-lamp-led",
    url: "assets/meshy/street/street-lamp-led.glb",
    category: "street",
    approxTriangles: 5910,
    bytes: 555408,
    license: MESHY_LICENSE,
    placementHint: "Every street edge on ~18 m spacing; night lighting anchor.",
  },
  {
    id: "street-lamp-neon",
    url: "assets/meshy/street/street-lamp-neon.glb",
    category: "street",
    approxTriangles: 6000,
    bytes: 280684,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter and arcade streets; alternates with street-lamp-led for night variety.",
  },
  {
    id: "street-mailbox",
    url: "assets/meshy/street/street-mailbox.glb",
    category: "street",
    approxTriangles: 4096,
    bytes: 178864,
    license: MESHY_LICENSE,
    placementHint: "Street corners near shop entrances; 1-2 per district.",
  },
  {
    id: "street-parcel-locker",
    url: "assets/meshy/street/street-parcel-locker.glb",
    category: "street",
    approxTriangles: 6064,
    bytes: 220472,
    license: MESHY_LICENSE,
    placementHint: "Courier quest hubs and residential frontages; futuristic sibling of street-mailbox.",
  },
  {
    id: "street-phone-booth",
    url: "assets/meshy/street/street-phone-booth.glb",
    category: "street",
    approxTriangles: 6427,
    bytes: 285240,
    license: MESHY_LICENSE,
    placementHint: "Street corners in Crystal Neon Quarter and Old Town; nostalgic cyber landmark, glows at night.",
  },
  {
    id: "street-planter-shrub",
    url: "assets/meshy/street/street-planter-shrub.glb",
    category: "street",
    approxTriangles: 7829,
    bytes: 347500,
    license: MESHY_LICENSE,
    placementHint: "Sidewalk greenery rows; Verdant Downtown density 2×.",
  },
  {
    id: "street-recycle-station",
    url: "assets/meshy/street/street-recycle-station.glb",
    category: "street",
    approxTriangles: 6582,
    bytes: 316900,
    license: MESHY_LICENSE,
    placementHint: "Plaza corners and dojo forecourts; bulkier sibling of street-trash-bin.",
  },
  {
    id: "street-scaffolding",
    url: "assets/meshy/street/street-scaffolding.glb",
    category: "street",
    approxTriangles: 7911,
    bytes: 304176,
    license: MESHY_LICENSE,
    placementHint: "Against building facades under renovation; tiles vertically and horizontally.",
  },
  {
    id: "street-scooter-shared",
    url: "assets/meshy/street/street-scooter-shared.glb",
    category: "street",
    approxTriangles: 5156,
    bytes: 264432,
    license: MESHY_LICENSE,
    placementHint: "Leaned near metro entrances, dojo doors and bike racks; scatter 1-3 per block.",
  },
  {
    id: "street-traffic-cone",
    url: "assets/meshy/street/street-traffic-cone.glb",
    category: "street",
    approxTriangles: 2404,
    bytes: 169060,
    license: MESHY_LICENSE,
    placementHint: "Clusters near road works, scaffolding and courier zones.",
  },
  {
    id: "street-traffic-signal",
    url: "assets/meshy/street/street-traffic-signal.glb",
    category: "street",
    approxTriangles: 5938,
    bytes: 262480,
    license: MESHY_LICENSE,
    placementHint: "Every signalled intersection; the road grid currently has no signals at all.",
  },
  {
    id: "street-trash-bin",
    url: "assets/meshy/street/street-trash-bin.glb",
    category: "street",
    approxTriangles: 4308,
    bytes: 190092,
    license: MESHY_LICENSE,
    placementHint: "Next to benches and food cart; 2-3 per block.",
  },
  {
    id: "street-utility-pole",
    url: "assets/meshy/street/street-utility-pole.glb",
    category: "street",
    approxTriangles: 5776,
    bytes: 291896,
    license: MESHY_LICENSE,
    placementHint: "Old Town lanes and Container Port back streets; overhead-cable grit between buildings.",
  },
  {
    id: "street-vending-machine",
    url: "assets/meshy/street/street-vending-machine.glb",
    category: "street",
    approxTriangles: 9039,
    bytes: 706336,
    license: MESHY_LICENSE,
    placementHint: "Building alcoves and dojo lobbies; emits soft light at night.",
  },
  {
    id: "street-vendor-stand",
    url: "assets/meshy/street/street-vendor-stand.glb",
    category: "street",
    approxTriangles: 9136,
    bytes: 306124,
    license: MESHY_LICENSE,
    placementHint: "Harborfront market rows and Old Town squares; NPC vendor anchor.",
  },
  {
    id: "structure-market-stall",
    url: "assets/meshy/structure/structure-market-stall.glb",
    category: "structure",
    approxTriangles: 11274,
    bytes: 757696,
    license: MESHY_LICENSE,
    placementHint: "Harborfront market square rows; walkable under the roof.",
  },
  {
    id: "structure-metro-entrance",
    url: "assets/meshy/structure/structure-metro-entrance.glb",
    category: "structure",
    approxTriangles: 16570,
    bytes: 397516,
    license: MESHY_LICENSE,
    placementHint: "One per district main street; fast-travel flavor anchor.",
  },
  {
    id: "structure-midrise-brick",
    url: "assets/meshy/structure/structure-midrise-brick.glb",
    category: "structure",
    approxTriangles: 28000,
    bytes: 516368,
    license: MESHY_LICENSE,
    placementHint: "Old Town street walls; alternates with glass-tech block.",
  },
  {
    id: "structure-midrise-glass",
    url: "assets/meshy/structure/structure-midrise-glass.glb",
    category: "structure",
    approxTriangles: 27999,
    bytes: 510648,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter and Verdant Downtown blocks; street-wall building.",
  },
  {
    id: "structure-plaza-fountain",
    url: "assets/meshy/structure/structure-plaza-fountain.glb",
    category: "structure",
    approxTriangles: 20313,
    bytes: 368876,
    license: MESHY_LICENSE,
    placementHint: "District plaza centerpieces; gathering point with benches around.",
  },
  {
    id: "structure-skybridge",
    url: "assets/meshy/structure/structure-skybridge.glb",
    category: "structure",
    approxTriangles: 18537,
    bytes: 486396,
    license: MESHY_LICENSE,
    placementHint: "Connects mid-rise blocks over streets; tiles end-to-end between facades.",
  },
  {
    id: "vehicle-box-truck",
    url: "assets/meshy/vehicle/vehicle-box-truck.glb",
    category: "vehicle",
    approxTriangles: 12145,
    bytes: 692128,
    license: MESHY_LICENSE,
    placementHint: "Container Port loading docks and alley deliveries.",
  },
  {
    id: "vehicle-courier-drone",
    url: "assets/meshy/vehicle/vehicle-courier-drone.glb",
    category: "vehicle",
    approxTriangles: 7702,
    bytes: 505976,
    license: MESHY_LICENSE,
    placementHint: "Hover traffic layer and courier beacon deliveries.",
  },
  {
    id: "vehicle-delivery-van",
    url: "assets/meshy/vehicle/vehicle-delivery-van.glb",
    category: "vehicle",
    approxTriangles: 13356,
    bytes: 693232,
    license: MESHY_LICENSE,
    placementHint: "Container Port loading bays and courier quest points.",
  },
  {
    id: "vehicle-hover-bus",
    url: "assets/meshy/vehicle/vehicle-hover-bus.glb",
    category: "vehicle",
    approxTriangles: 13749,
    bytes: 691708,
    license: MESHY_LICENSE,
    placementHint: "Bus stops and transit lanes; static dressing at shelters.",
  },
  {
    id: "vehicle-hover-pickup",
    url: "assets/meshy/vehicle/vehicle-hover-pickup.glb",
    category: "vehicle",
    approxTriangles: 13077,
    bytes: 897024,
    license: MESHY_LICENSE,
    placementHint: "Work-site curbs, Container Port yards and Mountain Outskirts driveways; fourth street-car silhouette.",
  },
  {
    id: "vehicle-hoverbike",
    url: "assets/meshy/vehicle/vehicle-hoverbike.glb",
    category: "vehicle",
    approxTriangles: 14053,
    bytes: 739540,
    license: MESHY_LICENSE,
    placementHint: "Player-rideable mount (Hoverboard upgrade path); origin at floating rest height.",
  },
  {
    id: "vehicle-hovercar-beater",
    url: "assets/meshy/vehicle/vehicle-hovercar-beater.glb",
    category: "vehicle",
    approxTriangles: 12912,
    bytes: 806608,
    license: MESHY_LICENSE,
    placementHint: "Old Town alleys and Container Port back streets; lived-in contrast to the showpiece cars.",
  },
  {
    id: "vehicle-hovercar-compact",
    url: "assets/meshy/vehicle/vehicle-hovercar-compact.glb",
    category: "vehicle",
    approxTriangles: 12096,
    bytes: 597228,
    license: MESHY_LICENSE,
    placementHint: "Residential curb parking; third sedan silhouette for variety.",
  },
  {
    id: "vehicle-hovercar-sedan",
    url: "assets/meshy/vehicle/vehicle-hovercar-sedan.glb",
    category: "vehicle",
    approxTriangles: 13421,
    bytes: 687932,
    license: MESHY_LICENSE,
    placementHint: "Street-side parking pads; static dressing, no animation.",
  },
  {
    id: "vehicle-hovercar-sport",
    url: "assets/meshy/vehicle/vehicle-hovercar-sport.glb",
    category: "vehicle",
    approxTriangles: 13710,
    bytes: 592436,
    license: MESHY_LICENSE,
    placementHint: "Crystal Neon Quarter and arcade frontage; showpiece parking.",
  },
  {
    id: "vehicle-hovercar-taxi",
    url: "assets/meshy/vehicle/vehicle-hovercar-taxi.glb",
    category: "vehicle",
    approxTriangles: 12926,
    bytes: 640532,
    license: MESHY_LICENSE,
    placementHint: "Taxi ranks near metro entrances and hotels; second sedan silhouette.",
  },
  {
    id: "vehicle-hovercar-wagon",
    url: "assets/meshy/vehicle/vehicle-hovercar-wagon.glb",
    category: "vehicle",
    approxTriangles: 11744,
    bytes: 784408,
    license: MESHY_LICENSE,
    placementHint: "Residential curb parking rows; fifth street-car silhouette, pairs with hovercar-compact.",
  },
  {
    id: "vehicle-security-drone",
    url: "assets/meshy/vehicle/vehicle-security-drone.glb",
    category: "vehicle",
    approxTriangles: 8251,
    bytes: 594012,
    license: MESHY_LICENSE,
    placementHint: "Hovers on patrol loops near arena and port; pairs with courier drone.",
  },
]

export const MESHY_MANIFEST: Record<string, MeshyAssetEntry> = Object.fromEntries(
  MESHY_ASSETS.map((entry) => [entry.id, entry]),
)

export function meshyAsset(id: string): MeshyAssetEntry | undefined {
  return MESHY_MANIFEST[id]
}

export function meshyAssetsByCategory(category: MeshyAssetCategory): MeshyAssetEntry[] {
  return MESHY_ASSETS.filter((entry) => entry.category === category)
}

/** Total bytes of the optimized Meshy library (budget-checked in CI). */
export const MESHY_TOTAL_BYTES = MESHY_ASSETS.reduce((sum, entry) => sum + entry.bytes, 0)
